export type Config={protocolVersion:1;authMode:'development'|'sessions'};
export type Failure={destination:string;turnCost:number;recoveryHealth:number;allowSurrender?:boolean;goldLossBps?:number;goldLossCap?:number;durabilityWearBps?:number;injuryEffectId?:string};
export type GameView={equipment?:EquipmentPlan;gear?:Gear[];loadouts?:Loadout[];hasMoreGear?:boolean;protocolVersion:1;run:{runId:string;turns:number;revision:number;status:string;mode:string};canWrite:boolean;activeEncounter:{id:string;kind:'TACTICAL'|'OTHER'}|null;latestEncounter:{id:string;name:string;outcome:string}|null;adventures:{id:string;name:string;description:Record<string,unknown>;turnCost:number;failure:Failure}[];inventory:{id:string;name:string;quantity:string;binding:string}[];hasMoreAdventures:boolean;hasMoreItems:boolean};
export type Progression={revision:number;level:number;xp:string;build:{mode:'CONFIGURED'|'UNCONFIGURED';classes?:{classId:string;nativeLevel:number}[];attributes?:Record<string,number>};readiness:{pendingLevels:number;nextThreshold:string|null}|null};
export type BuildOptions={classes:{classId:string;name:string;rulesId:string;maximumNativeLevel:number}[];rules:{rulesId:string;presets:{key:string;attributes:Record<string,number>}[]}[]};
export type Unit={id:string;side:'PARTY'|'ENEMY';zone:string;health:number;maxHealth:number;mana:number;maxMana:number;state:string;strikes:number;effects?:{effectId:string;family:string;polarity:string;remaining:number;clock:string;control?:string;removal?:{method:string;difficulty:number}}[];resources?:Record<string,number>;cooldowns?:Record<string,number>;concentration?:{token:string;abilityId:string}|null};
export type Capability={id:string;control?:'PLAYER'|'SERVER';heal:boolean;guard:boolean;attackAbilities?:{abilityId:string;range:number;manaCost:number}[];healingAbilities?:{abilityId:string;range:number;manaCost:number}[];cleansingAbilities?:{abilityId:string;method:string;manaCost:number;range:number;targetSide:string}[];techniques?:{abilityId:string;action:'MAIN'|'QUICK'|'REACTION';targetSide:'ALLY'|'ENEMY';range:number;manaCost:number;resourceCost:Record<string,number>;effect:{kind:string};concentration:boolean}[]};
export type Tactical={instanceId:string;revision:number;encounterRevision:number;tacticalRevision:number;round:number;currentActor:string|null;outcome:string|null;order:string[];units:Unit[];budgets:Record<string,{main:number;quick:number;reaction:number}>;partyCapabilities:Capability[];battlefield:{zones:string[];edges:[string,string][]};actionRules:{attackRange:number;healRange:number;healManaCost:number;healAmount:number;surrender?:boolean};failureContract:Failure;recovery:{destination:string;health:number;mana:number;turnCost:number;costs?:{goldLost:string;equipmentWear:{itemId:string;before:number;after:number;maximum:number}[]}}|null};
export type Command={actorId:string;kind:string;targetId?:string;abilityId?:string;effectId?:string;zone?:string};
export type Snapshot={game:GameView;progression:Progression;options:BuildOptions;battle:Tactical|null};
export type Notice={text:string;kind:'info'|'error'|'success'};

export type EquipmentAssignment={set:'WORN'|'A'|'B';slot:string;itemId:string};
export type EquipmentPlan={activeSet:'A'|'B';slots:EquipmentAssignment[]};
export type Gear={id:string;name:string;binding:string;slots:string[];hands:number;minimumLevel:number;bindingPolicy:string;eligible:boolean;proficiencyMet:boolean;manualLocked:boolean;protectedLoadouts:string[];condition:number|null;maximumCondition:number|null};
export type Loadout={key:string;name:string;plan:EquipmentPlan;protectItems:boolean};
