import { renderLanding } from './landing.js';
import { renderEquipment } from './equipment.js';
import type { GameSession } from './session.js';
import type { Command,Snapshot,Failure } from './types.js';
export type Screen='adventure'|'character'|'pack'|'combat';
let retainedFocus:string|null=null;
export const label=(value:string)=>value==='hero'?'You':value.split(/[._-]/).filter(Boolean).map(w=>w[0]!.toUpperCase()+w.slice(1).toLowerCase()).join(' ');
function el<K extends keyof HTMLElementTagNameMap>(tag:K,text='',className=''):HTMLElementTagNameMap[K]{const node=document.createElement(tag);node.textContent=text;if(className)node.className=className;return node;}
function add(node:HTMLElement,...children:(HTMLElement|null)[]){for(const child of children)if(child)node.append(child);return node;}
function button(text:string,action:()=>void,disabled=false,className=''){const b=el('button',text,className);b.type='button';b.dataset.focus=text;b.disabled=disabled;b.addEventListener('click',action);return b;}
function heading(text:string){const h=el('h1',text);h.tabIndex=-1;return h;}
function section(title:string){return add(el('section','','panel'),el('h2',title));}
function field(text:string,name:string,type='text'){const l=el('label',text),input=el('input');input.name=name;input.type=type;input.required=true;input.autocomplete=name==='token'?'off':type==='password'?'current-password':name==='handle'?'username':'off';l.append(input);return {label:l,input};}
export function render(root:HTMLElement,session:GameSession,screen:Screen,navigate:(screen:Screen)=>void,onCommand:(command:Command)=>void){
 const previousFocus=document.activeElement instanceof HTMLElement?document.activeElement.dataset.focus:null;
 if(previousFocus)retainedFocus=previousFocus;
 const fragment=document.createDocumentFragment(),top=el('header','','topbar');add(top,add(el('div','','wordmark'),el('span','REALMS'),el('small','A world worth wandering')));
 const disabled=session.busy||!!session.pending||session.needsRefresh||!session.snapshot?.game.canWrite;
 if(session.snapshot){const nav=el('nav');nav.setAttribute('aria-label','Game');for(const [key,title] of [['adventure','Adventure'],['character','Character'],['pack','Pack']] as const){const b=button(title,()=>navigate(key));b.setAttribute('aria-current',screen===key?'page':'false');nav.append(b);}add(top,nav,el('span',session.snapshot.game.canWrite?'Connected · Saved on server':'Viewing only','connection'),add(el('div','','tools'),button('Refresh',()=>void session.refresh(),session.busy,'small'),button('Sign out',()=>void session.logout(),session.busy||!!session.pending,'small')));}
 fragment.append(top);
 const notice=el('div','',`notice ${session.notice.kind}`);notice.setAttribute('role',session.notice.kind==='error'?'alert':'status');add(notice,el('span',session.busy?'Connecting to your saved game…':session.notice.text),session.pending&&!session.busy?button('Retry same action',()=>void session.retry(),session.busy,'small'):null);fragment.append(notice);
 const snapshot=session.snapshot;
 if(!snapshot){fragment.append(renderLanding(session));
 }else{
  const layout=el('div','','layout'),left=el('aside','','left-column'),character=section('The wayfarer');character.classList.add('character');character.prepend(el('div','✧','portrait'));add(character,el('small',snapshot.progression.build.mode==='CONFIGURED'?snapshot.progression.build.classes?.map(c=>`${snapshot.options.classes.find(option=>option.classId===c.classId)?.name??label(c.classId)} ${c.nativeLevel}`).join(' · ')??'Adventurer':'Choose your calling'),add(el('div','','stats'),stat('Level',String(snapshot.progression.level)),stat('Turns',String(snapshot.game.run.turns)),stat('XP',snapshot.progression.xp)),el('div','','rule'),el('p',snapshot.game.run.status==='AFTERCORE'?'Aftercore · A new chapter':'A life still being written','build-list muted'));left.append(character);
  const help=section('Your next step');add(help,el('p',snapshot.progression.build.mode!=='CONFIGURED'?'Choose a class and starting attributes to shape this life.':snapshot.game.activeEncounter?'Your encounter is saved. Continue from the current turn.':snapshot.progression.readiness?.pendingLevels?'You have earned a level. Choose how your character grows.':'Choose a known adventure. Each entry costs one Turn.','help'),button(snapshot.progression.build.mode!=='CONFIGURED'?'Create your build':'View character',()=>navigate('character'),false,'small'));left.append(help);
  const main=el('main');main.id='main';main.setAttribute('aria-busy',String(session.busy));
  if(screen==='character')renderCharacter(main,snapshot,session,disabled);
  else if(screen==='pack')renderPack(main,snapshot,session,disabled);
  else if(screen==='combat'&&snapshot.battle)renderCombat(main,snapshot,disabled,onCommand,navigate);
  else renderAdventure(main,snapshot,session,disabled,navigate);
  const right=el('aside','','right-column'),journal=section('Journey journal');add(journal,el('p','The moments that shape this life.','muted help'));
  if(snapshot.game.latestEncounter)add(journal,add(el('div','','journal-entry'),el('strong',snapshot.game.latestEncounter.name),el('p',label(snapshot.game.latestEncounter.outcome)),button('View encounter',()=>navigate('combat'),false,'link')));
  else journal.append(el('p','Your first adventure is still ahead.','help'));
  if(snapshot.game.activeEncounter)add(journal,add(el('div','','journal-entry'),el('strong','Encounter in progress'),el('p','Reconnect resumes the same fight.')));
  const guide=section('A few things to know');add(guide,el('p','Explore at your own pace. Browsing your character, pack, and saved encounter costs no Turns.','help'),el('p','Choose actions during your turn. The server resolves opponents and automated companions, then returns control to your party.','help'),el('p','Victory rewards and recovery are saved automatically.','help'));add(right,journal,guide);add(layout,left,main,right);fragment.append(layout);
 }
 fragment.append(el('footer','Realms · A living world, one journey at a time.','footer'));root.replaceChildren(fragment);
 if(!session.busy&&retainedFocus){const matching=Array.from(root.querySelectorAll<HTMLElement>('[data-focus]')).find(e=>e.dataset.focus===retainedFocus);if(matching&&!(matching instanceof HTMLButtonElement&&matching.disabled))matching.focus();else root.querySelector<HTMLElement>('main h1')?.focus();retainedFocus=null;}
}
function stat(name:string,value:string){return add(el('div','','stat'),el('strong',value),el('span',name));}
function renderAdventure(main:HTMLElement,s:Snapshot,session:GameSession,disabled:boolean,navigate:(s:Screen)=>void){
 add(main,add(el('section','','panel hero'),el('span','Your journey','eyebrow'),heading('Follow the road.'),el('p','A familiar path can still hold an unfamiliar story. Choose where your next Turn takes you.')));
 add(main,add(el('div','','section-header'),el('h2','Known adventures'),el('small',`${s.game.adventures.length} discovered`)));
 if(s.game.activeEncounter){main.append(add(el('section','','panel'),el('h3','Your adventure is already underway'),el('p',s.game.activeEncounter.kind==='TACTICAL'?'Return to your saved encounter before beginning another.':'This saved encounter uses controls that are not available in this client yet.'),s.game.activeEncounter.kind==='TACTICAL'?button('Resume encounter',()=>navigate('combat'),false,'primary'):null));return;}
 if(!s.game.adventures.length){main.append(el('p','No adventures have been discovered in this run yet. New content will appear here as you discover it.','empty'));return;}
 const cards=el('div','','cards');for(const adventure of s.game.adventures){const summary=typeof adventure.description.summary==='string'?adventure.description.summary:'A known encounter awaits. Prepare your character before setting out.';const unavailable=disabled||s.game.run.turns<adventure.turnCost||s.progression.build.mode!=='CONFIGURED';const card=add(el('article','','panel adventure'),el('span','⌁','crest'),el('h3',adventure.name),el('p',summary,'description'),el('div',`Entry: ${adventure.turnCost} Turn. ${failureSummary(adventure.failure)}`,'cost'),button(`Begin · ${adventure.turnCost} Turn`,()=>{navigate('combat');void session.action('/api/v1/tactical/start','START_TACTICAL',{definitionId:adventure.id});},unavailable,'primary'));if(unavailable)card.append(el('small',!s.game.canWrite?'This session is view only.':s.progression.build.mode!=='CONFIGURED'?'Choose your starting build first.':s.game.run.turns<adventure.turnCost?'You need more Turns.':'Wait for the current action or refresh to reconnect.'));cards.append(card);}main.append(cards);if(s.game.hasMoreAdventures)main.append(el('p','Showing the first 100 discovered adventures.','help'));
}
function renderCharacter(main:HTMLElement,s:Snapshot,session:GameSession,disabled:boolean){
 add(main,heading('Shape your character.'),el('p','A class is a starting point. The choices ahead will make it yours.','muted'));
 if(s.progression.build.mode!=='CONFIGURED'){
  if(!s.options.classes.length){main.append(el('p','There are no discovered starting classes available for this run.','empty'));return;}
  const cards=el('div','','cards');for(const c of s.options.classes){const card=add(el('article','','panel'),el('h2',c.name));for(const preset of s.options.rules.find(r=>r.rulesId===c.rulesId)?.presets??[]){add(card,el('h3',label(preset.key)),el('p',Object.entries(preset.attributes).map(([name,n])=>`${label(name)} ${n}`).join(' · '),'help'),button(`Choose ${c.name} · ${label(preset.key)}`,()=>void session.action('/api/v1/progression/start','START_BUILD',{classId:c.classId,presetKey:preset.key}),disabled,'primary'));}cards.append(card);}main.append(cards);
 }else{
  const sheet=section('Attributes'),attributes=el('div','','attributes');for(const [name,n] of Object.entries(s.progression.build.attributes??{}))attributes.append(add(el('div','','attribute'),el('span',label(name)),el('strong',String(n))));add(sheet,attributes);main.append(sheet);
  if(s.progression.readiness?.pendingLevels){const progression=section('An earned level');add(progression,el('p','Choose the class that grows with you. The server checks your earned level and class limits.'));for(const c of s.options.classes)add(progression,button(`Grow as ${c.name}`,()=>void session.action('/api/v1/progression/level','LEVEL_UP',{classId:c.classId}),disabled||!!s.game.activeEncounter,'small'));main.append(progression);}
  else main.append(el('p','Your next level becomes available through earned experience.','empty'));
 }
}
function renderPack(main:HTMLElement,s:Snapshot,session:GameSession,disabled:boolean){add(main,heading('What you carry.'),el('p','Equipment, materials, and the small treasures collected along the way.','muted'));const pack=section('Your pack');for(const item of s.game.inventory)add(pack,add(el('div','','pack-row'),add(el('div'),el('strong',item.name),el('small',label(item.binding))),el('strong',`× ${item.quantity}`)));if(!s.game.inventory.length)pack.append(el('p','Your pack is empty.','muted'));if(s.game.hasMoreItems)pack.append(el('p','Showing the first 100 carried items.','help'));main.append(pack);renderEquipment(main,s,session,disabled);}
function renderCombat(main:HTMLElement,s:Snapshot,disabled:boolean,send:(c:Command)=>void,navigate:(s:Screen)=>void){
 const b=s.battle!;add(main,add(el('div','','battle-top'),add(el('div'),el('span',`Round ${b.round}`,'eyebrow'),heading(b.outcome?'An encounter remembered.':'Choose your next move.')),el('span',b.outcome?label(b.outcome):b.currentActor==='hero'?'Your turn':`${label(b.currentActor??'')} acts next`,'tag')));
 const battlefield=el('div','','battlefield');for(const zone of b.battlefield.zones){const box=add(el('section','','zone'),el('h3',label(zone))),units=el('div','','units');for(const u of b.units.filter(u=>u.zone===zone)){const card=add(el('article','',`unit ${u.side.toLowerCase()} ${u.id===b.currentActor?'current':''}`),el('strong',label(u.id)),el('p',`${u.health} / ${u.maxHealth} health · ${label(u.state)}`));const meter=el('div','','meter'),filled=el('span'),missing=el('span');filled.style.flexGrow=String(u.health);missing.className='missing';missing.style.flexGrow=String(Math.max(0,u.maxHealth-u.health));add(card,add(meter,filled,missing),el('p',`${u.mana} / ${u.maxMana} Mana`));for(const effect of u.effects??[])card.append(el('p',`${label(effect.family)} · ${effect.remaining} ${label(effect.clock)}`,'tag'));units.append(card);}box.append(units);battlefield.append(box);}main.append(battlefield);
 if(b.outcome){const result=section(label(b.outcome));result.classList.add('outcome');add(result,el('p',b.outcome==='VICTORY'?'Your rewards and experience have been saved.':'The outcome and your recovery have been saved.'),b.recovery?el('p',`${label(b.recovery.destination)} · ${b.recovery.health} health · ${b.recovery.mana} Mana · ${b.recovery.turnCost} recovery Turns`):null,b.recovery?.costs?el('p',`Gold lost: ${b.recovery.costs.goldLost}. Equipment wear: ${b.recovery.costs.equipmentWear.length?b.recovery.costs.equipmentWear.map(w=>`${w.before} → ${w.after} / ${w.maximum}`).join(' · '):'none'}.`,'help'):null,button('Return to the road',()=>navigate('adventure'),false,'primary'),button('View your pack',()=>navigate('pack'),false,'small'));main.append(result);return;}
 const actor=b.units.find(u=>u.id===b.currentActor),cap=b.partyCapabilities.find(c=>c.id===b.currentActor);if(!actor)return;
 const panel=section(actor.side==='ENEMY'||cap?.control==='SERVER'?'The world takes its turn':`${label(actor.id)} · Your turn`);
 if(actor.side==='ENEMY'||cap?.control==='SERVER'){add(panel,el('p','Continue the next saved segment of combat. No actions continue while you are disconnected.'),button('Continue',()=>send({actorId:'hero',kind:'CONTINUE'}),disabled,'primary'));main.append(panel);return;}
 const budget=b.budgets[actor.id]!,targetLabel=el('label','Choose a target'),target=el('select');target.dataset.focus='combat-target';target.setAttribute('aria-label','Choose a target');for(const u of b.units){const option=el('option',`${label(u.id)} · ${u.health} health · ${label(u.state)}`);option.value=u.id;target.append(option);}target.value=b.units.find(u=>u.side!==actor.side&&u.state==='ACTIVE')?.id??actor.id;targetLabel.append(target);panel.append(targetLabel);
 add(panel,el('p',`Main ${budget.main} · Quick ${budget.quick} · Reaction ${budget.reaction}`,'budget'));
 const actions=el('div','','actions');const current=()=>b.units.find(u=>u.id===target.value)!;
 const targetAction=(title:string,kind:string,range:number,side:'ALLY'|'ENEMY',cost=0,abilityId?:string)=>{const btn=button(title,()=>send({actorId:actor.id,kind,targetId:current().id,...(abilityId?{abilityId}:{})}),disabled,'small');const sync=()=>{const u=current();const legalSide=side==='ALLY'?u.side===actor.side:u.side!==actor.side;const distance=zoneDistance(b.battlefield.edges,actor.zone,u.zone);btn.disabled=disabled||budget.main===0||actor.mana<cost||!legalSide||distance>range||(side==='ENEMY'?u.state!=='ACTIVE':u.state==='DEFEATED');btn.title=btn.disabled?'Requires an available Main action, an eligible target in range, and enough Mana.':'';};target.addEventListener('change',sync);sync();actions.append(btn);};
 targetAction('Attack','ATTACK',b.actionRules.attackRange,'ENEMY');if(cap?.heal)targetAction(`Heal · ${b.actionRules.healManaCost} Mana`,'HEAL',b.actionRules.healRange,'ALLY',b.actionRules.healManaCost);if(cap?.guard)actions.append(button('Guard',()=>send({actorId:actor.id,kind:'GUARD'}),disabled||budget.quick!==1,'small'));
 for(const a of cap?.attackAbilities??[])targetAction(`${label(a.abilityId)} · ${a.manaCost} Mana`,'USE_ABILITY',a.range,'ENEMY',a.manaCost,a.abilityId);for(const a of cap?.healingAbilities??[])targetAction(`${label(a.abilityId)} · ${a.manaCost} Mana`,'USE_HEALING_ABILITY',a.range,'ALLY',a.manaCost,a.abilityId);
 for(const a of cap?.techniques??[]){if(a.action==='REACTION')continue;const btn=button(`${label(a.abilityId)} · ${label(a.action)} · ${a.manaCost} Mana`,()=>send({actorId:actor.id,kind:'TECHNIQUE',targetId:current().id,abilityId:a.abilityId}),disabled,'small');const sync=()=>{const u=current();btn.disabled=disabled||budget[a.action==='MAIN'?'main':'quick']===0||actor.mana<a.manaCost||(actor.cooldowns?.[a.abilityId]??0)>b.round||Object.entries(a.resourceCost).some(([k,n])=>(actor.resources?.[k]??0)<n)||(a.targetSide==='ALLY'?u.side!==actor.side:u.side===actor.side)||zoneDistance(b.battlefield.edges,actor.zone,u.zone)>a.range||(a.effect.kind==='RESURRECT'?u.state!=='DEFEATED':a.effect.kind==='STABILIZE'?u.state!=='DOWNED':a.effect.kind==='HEAL'?u.state==='DEFEATED':u.state!=='ACTIVE');btn.title=btn.disabled?'Requires the shown action, resources, cooldown, and an eligible target in range.':Object.entries(a.resourceCost).map(([k,n])=>`${label(k)}: ${n}`).join(', ');};target.addEventListener('change',sync);sync();actions.append(btn);}
 for(const a of cap?.cleansingAbilities??[]){const row=el('div','','actions');for(const u of b.units)for(const effect of u.effects??[])if(effect.removal?.method===a.method){const btn=button(`${label(a.method)} ${label(effect.family)} on ${label(u.id)}`,()=>send({actorId:actor.id,kind:'CLEANSE',abilityId:a.abilityId,targetId:u.id,effectId:effect.effectId}),disabled||budget.main===0||actor.mana<a.manaCost||zoneDistance(b.battlefield.edges,actor.zone,u.zone)>a.range,'small');row.append(btn);}panel.append(row);}
 panel.append(actions);if(actor.resources&&Object.keys(actor.resources).length)panel.append(el('p',Object.entries(actor.resources).map(([k,n])=>`${label(k)} ${n}`).join(' · '),'help'));
 const movement=add(el('div','','action-group'),el('h3','Position'));for(const zone of b.battlefield.zones.filter(z=>z!==actor.zone&&b.battlefield.edges.some(([a,c])=>a===actor.zone&&c===z||c===actor.zone&&a===z)))movement.append(button(`Move to ${label(zone)}`,()=>send({actorId:actor.id,kind:'MOVE',zone}),disabled||budget.quick===0,'small'));panel.append(movement);
 add(panel,add(el('div','','actions'),button('End turn',()=>send({actorId:actor.id,kind:'END'}),disabled,'primary'),actor.concentration?button('Drop concentration',()=>send({actorId:actor.id,kind:'DROP_CONCENTRATION'}),disabled,'small'):null,button('Attempt retreat',()=>send({actorId:actor.id,kind:'RETREAT'}),disabled||budget.main===0,'small'),b.actionRules.surrender?button('Surrender',()=>{if(confirm('Surrender ends this encounter for the party and applies its disclosed recovery costs. Continue?'))send({actorId:actor.id,kind:'SURRENDER'});},disabled,'small danger'):null),el('p',failureSummary(b.failureContract),'tooltip'));main.append(panel);
}
export function zoneDistance(edges:[string,string][],from:string,to:string){if(from===to)return 0;const queue:[string,number][]=[[from,0]],seen=new Set([from]);for(const [zone,distance] of queue)for(const [a,b] of edges){const next=a===zone?b:b===zone?a:null;if(next&&!seen.has(next)){if(next===to)return distance+1;seen.add(next);queue.push([next,distance+1]);}}return Infinity;}

export function failureSummary(f:Failure){return `Defeat: ${label(f.destination)}, up to ${f.turnCost} recovery Turns; ${f.recoveryHealth} health.`+(f.goldLossBps!==undefined?` Eligible Gold loss: ${f.goldLossBps/100}%, capped at ${f.goldLossCap??0}. Active equipment wear: ${(f.durabilityWearBps??0)/100}%.`:'')+(f.injuryEffectId?` Injury: ${label(f.injuryEffectId)}.`:'')+(f.allowSurrender?' Surrender applies the same failure costs.':'');}
