import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { testDatabase,actor } from './helpers.js';
import { tacticalPackage,envelope } from './tactical-fixture.js';
import { publishContent } from '../src/domains/content.js';
import { enrollPassword,requireLogin } from '../src/auth/sessions.js';
import { buildApp } from '../src/app.js';
import { integrityReport } from '../src/foundation/integrity.js';

test('client shell is public and inert, while bootstrap protects account discovery, pinned content and session write scope',async()=>{
 const db=await testDatabase(),app=buildApp(db.pool,{mode:'sessions',throttleKey:'a'.repeat(64)});try{
  const p=tacticalPackage(),hidden=structuredClone(p.entities.find(e=>e.id==='encounter.tactical')!);hidden.id='encounter.secret';hidden.definition.name='Secret encounter';p.entities.push(hidden);const release=await publishContent(db.pool,p),f=await actor(db.pool,release,20),other=await actor(db.pool,release,20);await enrollPassword(db.pool,f.account,'client_user','A secure test password 47!');await enrollPassword(db.pool,other.account,'other_client','A secure test password 47!');await db.pool.query("INSERT INTO discoveries(account_id,entity_id,knowledge_level) VALUES($1,'encounter.tactical','LEARNED')",[f.account]);
  const shell=await app.inject('/');assert.equal(shell.statusCode,200);assert.match(shell.body,/id="app"/);assert.ok(shell.headers['content-security-policy']);assert.equal(shell.headers['cache-control'],'no-store');assert.ok(!shell.body.includes('Secret encounter'));assert.equal((await app.inject('/assets/../../.env')).statusCode,404);assert.equal((await app.inject('/api/v1/client/state')).statusCode,401);
  const login=await requireLogin(db.pool,'client_user','A secure test password 47!','Browser'),headers={authorization:`Bearer ${login.token}`};const snapshot=(await app.inject({url:'/api/v1/client/state',headers})).json();assert.equal(snapshot.canWrite,true);assert.equal(snapshot.run.runId,f.run);assert.deepEqual(snapshot.adventures.map((v:{id:string})=>v.id),['encounter.tactical']);const serialized=JSON.stringify(snapshot);for(const word of ['tacticalCombat','seed','lootTableId','monster.tactical','secret'])assert.ok(!serialized.includes(word),word);
  const ro=await requireLogin(db.pool,'client_user','A secure test password 47!','Read only',true),readonly={authorization:`Bearer ${ro.token}`};assert.equal((await app.inject({url:'/api/v1/client/state',headers:readonly})).json().canWrite,false);assert.equal((await app.inject({method:'POST',url:'/api/v1/tactical/start',headers:readonly,payload:{...envelope(0,'START_TACTICAL'),definitionId:'encounter.tactical'}})).statusCode,403);
  const foreign=await requireLogin(db.pool,'other_client','A secure test password 47!','Other');assert.equal((await app.inject({url:'/api/v1/client/state',headers:{authorization:`Bearer ${foreign.token}`}})).json().adventures.length,0);assert.equal((await db.pool.query('SELECT revision,turns FROM runs WHERE id=$1',[f.run])).rows[0].revision,0);
 }finally{await app.close();await db.close();}
});
test('client API completes starting build, saved encounter reconnect, victory rewards, recovery and earned level through authoritative routes',async()=>{
 const db=await testDatabase(),app=buildApp(db.pool,{mode:'sessions',throttleKey:'b'.repeat(64)});try{
  const release=await publishContent(db.pool,tacticalPackage()),f=await actor(db.pool,release,20);for(const id of ['class.one','encounter.tactical'])await db.pool.query("INSERT INTO discoveries(account_id,entity_id,knowledge_level) VALUES($1,$2,'DISCOVERED')",[f.account,id]);await db.pool.query("INSERT INTO inventory_containers(scope_id,kind) SELECT id,'CARRIED' FROM state_scopes WHERE run_id=$1",[f.run]);await enrollPassword(db.pool,f.account,'client_loop','A secure test password 47!');const login=await requireLogin(db.pool,'client_loop','A secure test password 47!','Browser'),headers={authorization:`Bearer ${login.token}`};
  async function post(url:string,payload:Record<string,unknown>){const r=await app.inject({method:'POST',url,headers,payload});assert.equal(r.statusCode,200,r.body);return r.json();}
  const options=(await app.inject({url:'/api/v1/progression/options',headers})).json();assert.equal(options.classes[0].classId,'class.one');await post('/api/v1/progression/start',{requestId:randomUUID(),actionType:'START_BUILD',expectedRevision:0,classId:'class.one',presetKey:'balanced'});
  const startPayload={...envelope(1,'START_TACTICAL'),definitionId:'encounter.tactical'};let v=await post('/api/v1/tactical/start',startPayload);const resume=(await app.inject({url:'/api/v1/client/state',headers})).json();assert.equal(resume.activeEncounter.id,v.instanceId);assert.equal(resume.activeEncounter.kind,'TACTICAL');assert.equal((await app.inject({url:`/api/v1/tactical/${v.instanceId}`,headers})).json().tacticalRevision,0);const duplicate=await post('/api/v1/tactical/start',startPayload);assert.equal(duplicate.replayed,true);assert.equal(duplicate.instanceId,v.instanceId);
  for(let i=0;i<100&&!v.outcome;i++){const current=v.units.find((u:{id:string})=>u.id===v.currentActor),enemy=v.units.find((u:{side:string;state:string})=>u.side==='ENEMY'&&u.state==='ACTIVE');const command=current.side==='ENEMY'?{actorId:'hero',kind:'CONTINUE'}:v.budgets[current.id].main?{actorId:current.id,kind:'ATTACK',targetId:enemy.id}:{actorId:current.id,kind:'END'};v=await post('/api/v1/tactical/actions',{...envelope(v.revision),instanceId:v.instanceId,expectedEncounterRevision:v.encounterRevision,expectedTacticalRevision:v.tacticalRevision,command});}
  assert.equal(v.outcome,'VICTORY');assert.ok(v.recovery);const saved=(await app.inject({url:'/api/v1/client/state',headers})).json();assert.equal(saved.activeEncounter,null);assert.equal(saved.latestEncounter.id,v.instanceId);assert.equal(saved.latestEncounter.outcome,'VICTORY');assert.equal(saved.inventory[0].name,'Ore');assert.equal(saved.inventory[0].quantity,'2');assert.equal(saved.run.turns,19);const progression=(await app.inject({url:'/api/v1/progression',headers})).json();assert.equal(progression.xp,'100');assert.equal(progression.readiness.pendingLevels,1);await post('/api/v1/progression/level',{...envelope(saved.run.revision,'LEVEL_UP'),classId:'class.one'});assert.equal((await app.inject({url:'/api/v1/progression',headers})).json().level,2);assert.ok(Object.values(await integrityReport(db.pool)).every(n=>n===0));
 }finally{await app.close();await db.close();}
});
