import test from 'node:test';
import assert from 'node:assert/strict';
import { normalizeAttackAbilities,validateAttackAbility,type AttackAbility } from '../src/domains/tactical-abilities.js';
import { startTactical,stepTactical,type TacticalRules,type TacticalUnit } from '../src/domains/tactical-engine.js';
const rules:TacticalRules={damage:{version:1,ruleset:'TACTICAL_DAMAGE_V1',check:{version:1,ruleset:'D20_CHECK_V1',attributeDivisor:2,attributeBaseline:10,proficiencyPerRank:2,natural20:'SUCCESS',natural1:'NORMAL'},criticalOn20:false,criticalMultiplierBps:20000,minimumConnectedDamage:1},zones:['floor','tower'],edges:[['floor','tower']],attackRange:0,healRange:0,healAmount:2,roundLimit:5,guardArmorBonus:3,abilities:{version:1},typedDamage:{version:1,types:['fire','slashing'],defaultType:'slashing',resistanceStacking:'SUM_CAPPED'}};
const ability=():AttackAbility=>({id:'class.one',sourceRevision:2,sourceInstanceIds:[],spec:{version:1,minimumNativeLevel:1,range:1,manaCost:2,accuracyModifier:1,damage:{type:'fire',min:10,max:10,penetration:2}}});
const unit=(id:string,side:TacticalUnit['side'],initiative:number):TacticalUnit=>({id,side,zone:'floor',health:30,strikes:0,state:'ACTIVE',stats:{maxHealth:30,maxMana:6,accuracy:20,evasion:10,armor:4,initiative,attackMin:3,attackMax:3}});
function initial(){const hero=unit('hero','PARTY',2),enemy=unit('enemy','ENEMY',1);hero.attackAbilities=[ability()];hero.damageProfile={version:1,attackType:'slashing',penetration:20,resistances:{}};enemy.zone='tower';enemy.damageProfile={version:1,attackType:'slashing',penetration:0,resistances:{fire:5000}};return startTactical(rules,[hero,enemy]);}
const use=(s:ReturnType<typeof initial>,roll=10)=>stepTactical(rules,s,s.revision,{actorId:'hero',kind:'USE_ABILITY',targetId:'enemy',abilityId:'class.one',roll,rawDamage:10});
test('selected offensive ability uses authored range/type/penetration and spends Main/mana with pinned provenance',()=>{const s=initial(),before=structuredClone(s),result=use(s);assert.deepEqual(s,before);assert.equal(result.state.units[1]!.health,26);assert.equal(result.state.units[0]!.mana,4);assert.equal(result.state.budgets.hero!.main,0);assert.equal(result.evidence.attack!.effectiveArmor,2);assert.equal(result.evidence.attack!.check.situationalModifier,21);assert.equal(result.evidence.damageType,'fire');assert.deepEqual(result.evidence.abilityEvents,[{actorId:'hero',targetId:'enemy',abilityId:'class.one',sourceRevision:2,sourceInstanceIds:[],manaCost:2}]);assert.throws(()=>use(result.state),/MAIN/);});
test('misses spend authored mana and Main; guard, immunity and criticals follow existing damage rules',()=>{const s=initial();s.units[1]!.stats.evasion=100;const miss=use(s);assert.equal(miss.evidence.attack!.damage,0);assert.equal(miss.state.units[0]!.mana,4);const guard=initial();guard.units[1]!.canGuard=true;guard.units[1]!.guardReady=true;assert.equal(use(guard).evidence.attack!.effectiveArmor,5);assert.equal(use(guard).state.budgets.enemy!.reaction,0);const immune=initial();immune.units[1]!.damageProfile!.resistances.fire=10000;assert.equal(use(immune).evidence.attack!.damage,0);const critical=stepTactical({...rules,damage:{...rules.damage,criticalOn20:true}},initial(),0,{actorId:'hero',kind:'USE_ABILITY',targetId:'enemy',abilityId:'class.one',roll:20,rawDamage:10});assert.equal(critical.evidence.attack!.critical,true);assert.equal(critical.evidence.attack!.damage,9);});
test('unowned abilities, wrong side/range, insufficient mana, forged magnitude and stale intents cannot mutate state',()=>{for(const mutate of [(s:ReturnType<typeof initial>)=>{s.units[0]!.attackAbilities=[];},(s:ReturnType<typeof initial>)=>{s.units[0]!.mana=1;},(s:ReturnType<typeof initial>)=>{s.units[0]!.attackAbilities![0]!.spec.range=0;}]){const s=initial();mutate(s);const before=structuredClone(s);assert.throws(()=>use(s));assert.deepEqual(s,before);}const s=initial(),before=structuredClone(s);for(const patch of [{targetId:'hero'},{rawDamage:99},{abilityId:'class.unknown'}])assert.throws(()=>stepTactical(rules,s,0,{actorId:'hero',kind:'USE_ABILITY',targetId:'enemy',abilityId:'class.one',roll:10,rawDamage:10,...patch}));assert.throws(()=>stepTactical(rules,s,1,{actorId:'hero',kind:'END'}),/STALE/);assert.deepEqual(s,before);});
test('identical equipped copies grant one choice without power stacking and retain all sorted instance identities',()=>{const a=ability(),b=ability();a.sourceInstanceIds=['11111111-1111-1111-1111-111111111111'];b.sourceInstanceIds=['22222222-2222-2222-2222-222222222222'];const forward=normalizeAttackAbilities([a,b],rules.typedDamage!);assert.deepEqual(forward,normalizeAttackAbilities([b,a],rules.typedDamage!));assert.equal(forward.length,1);assert.equal(forward[0]!.spec.damage.min,10);assert.equal(forward[0]!.sourceInstanceIds.length,2);b.spec.manaCost=1;assert.throws(()=>normalizeAttackAbilities([a,b],rules.typedDamage!),/CONFLICTING/);});
test('strict definitions and explicit typed opt-in reject free, inverted, ambiguous and unsupported ability contracts',()=>{for(const patch of [{manaCost:0},{range:32},{accuracyModifier:1001},{version:2},{damage:{type:'fire',min:11,max:10,penetration:0}},{cooldown:1}])assert.throws(()=>validateAttackAbility({...ability().spec,...patch}));const a=ability();a.spec.damage.type='void';assert.throws(()=>normalizeAttackAbilities([a],rules.typedDamage!),/UNKNOWN/);assert.throws(()=>startTactical({...rules,typedDamage:undefined},[unit('hero','PARTY',2),unit('enemy','ENEMY',1)]),/REQUIRE/);});
test('unopted encounters retain original state/evidence shapes and attacks',()=>{const {abilities,...r}=rules;const s=startTactical(r,[unit('hero','PARTY',2),unit('enemy','ENEMY',1)]);assert.ok(!Object.hasOwn(s.units[0]!,'attackAbilities'));const result=stepTactical(r,s,0,{actorId:'hero',kind:'ATTACK',targetId:'enemy',roll:10,rawDamage:3});assert.ok(!Object.hasOwn(result.evidence,'abilityEvents'));const hero=unit('hero','PARTY',2);hero.attackAbilities=[ability()];assert.throws(()=>startTactical(r,[hero,unit('enemy','ENEMY',1)]),/DISABLED/);});
