import test from 'node:test';
import assert from 'node:assert/strict';
import { abilityResistance,validateAttackAbility,type AttackAbility } from '../src/domains/tactical-abilities.js';
import { startTactical,stepTactical,type TacticalRules,type TacticalUnit } from '../src/domains/tactical-engine.js';
const rules:TacticalRules={damage:{version:1,ruleset:'TACTICAL_DAMAGE_V1',check:{version:1,ruleset:'D20_CHECK_V1',attributeDivisor:2,attributeBaseline:10,proficiencyPerRank:2,natural20:'SUCCESS',natural1:'NORMAL'},criticalOn20:false,criticalMultiplierBps:20000,minimumConnectedDamage:1},zones:['floor'],edges:[],attackRange:0,healRange:0,healAmount:2,roundLimit:5,guardArmorBonus:3,abilities:{version:2},typedDamage:{version:1,types:['fire','slashing'],defaultType:'slashing',resistanceStacking:'SUM_CAPPED'}};
const ability=(reduction=4000,bypass=false):AttackAbility=>({id:'class.one',sourceRevision:2,sourceInstanceIds:[],spec:{version:2,minimumNativeLevel:1,range:0,manaCost:2,accuracyModifier:0,damage:{type:'fire',min:10,max:10,penetration:2,resistanceReductionBps:reduction,bypassImmunity:bypass}}});
const unit=(id:string,side:TacticalUnit['side'],initiative:number):TacticalUnit=>({id,side,zone:'floor',health:30,strikes:0,state:'ACTIVE',stats:{maxHealth:30,maxMana:6,accuracy:20,evasion:10,armor:4,initiative,attackMin:3,attackMax:3}});
function initial(resistance=6000,reduction=4000,bypass=false){const hero=unit('hero','PARTY',2),enemy=unit('enemy','ENEMY',1);hero.attackAbilities=[ability(reduction,bypass)];enemy.damageProfile={version:1,attackType:'slashing',penetration:0,resistances:{fire:resistance}};return startTactical(rules,[hero,enemy]);}
const use=(s:ReturnType<typeof initial>,roll=20,r=rules)=>stepTactical(r,s,0,{actorId:'hero',kind:'USE_ABILITY',targetId:'enemy',abilityId:'class.one',roll,rawDamage:10});
test('selected resistance reduction applies after armor/penetration, spends Main/mana and leaves pinned defenses unchanged',()=>{const s=initial(),before=structuredClone(s),result=use(s);assert.deepEqual(s,before);assert.equal(result.evidence.attack!.effectiveArmor,2);assert.equal(result.evidence.attack!.damage,6);assert.equal(result.state.units[0]!.mana,4);assert.equal(result.state.budgets.hero!.main,0);assert.equal(result.state.units[1]!.damageProfile!.resistances.fire,6000);assert.deepEqual(result.evidence.resistanceEvents,[{actorId:'hero',targetId:'enemy',abilityId:'class.one',damageType:'fire',baseResistanceBps:6000,resistanceReductionBps:4000,bypassedImmunity:false,effectiveResistanceBps:2000}]);});
test('reduction alone preserves immunity; explicit matching bypass neutralizes immunity before bounded reduction',()=>{assert.equal(use(initial(10000,10000,false)).evidence.attack!.damage,0);const bypass=use(initial(10000,0,true));assert.equal(bypass.evidence.attack!.damage,8);assert.equal(bypass.evidence.resistanceEvents![0]!.bypassedImmunity,true);const combined=use(initial(10000,2500,true));assert.equal(combined.evidence.attack!.damage,10);assert.equal(combined.evidence.resistanceEvents![0]!.effectiveResistanceBps,-2500);assert.equal(use(initial(5000,0,true)).evidence.attack!.damage,4);});
test('vulnerability is bounded, guard/criticals retain their order and misses still spend resources',()=>{assert.equal(abilityResistance(ability(10000).spec,-9000).effectiveResistanceBps,-10000);const s=initial();s.units[1]!.canGuard=true;s.units[1]!.guardReady=true;assert.equal(use(s).evidence.attack!.damage,4);assert.equal(use(s).state.budgets.enemy!.reaction,0);assert.equal(use(initial(),20,{...rules,damage:{...rules.damage,criticalOn20:true}}).evidence.attack!.damage,14);const miss=initial();miss.units[1]!.stats.evasion=100;assert.equal(use(miss,10).evidence.attack!.damage,0);assert.equal(use(miss).state.units[0]!.mana,4);});
test('strict version gates reject missing/fractional/out-of-bounds counterplay or granting it to version-one abilities',()=>{const a=ability();for(const patch of [{resistanceReductionBps:-1},{resistanceReductionBps:10001},{resistanceReductionBps:0.5},{bypassImmunity:1},{bypassArmor:true}])assert.throws(()=>validateAttackAbility({...a.spec,damage:{...a.spec.damage,...patch}}));const incomplete={type:'fire',min:10,max:10,penetration:2,bypassImmunity:false};assert.throws(()=>validateAttackAbility({...a.spec,damage:incomplete}));assert.throws(()=>validateAttackAbility({...a.spec,version:1}));const hero=unit('hero','PARTY',2);hero.attackAbilities=[a];assert.throws(()=>startTactical({...rules,abilities:{version:1}},[hero,unit('enemy','ENEMY',1)]),/DISABLED/);const s=initial();assert.throws(()=>use(s,20,{...rules,abilities:{version:1}}),/DISABLED/);});
test('basic attacks and version-one abilities gain no counterplay; old evidence shape is unchanged',()=>{const s=initial(10000,10000,true);s.units[0]!.damageProfile={version:1,attackType:'fire',penetration:2,resistances:{}};const basic=stepTactical(rules,s,0,{actorId:'hero',kind:'ATTACK',targetId:'enemy',roll:20,rawDamage:3});assert.equal(basic.evidence.attack!.damage,0);assert.deepEqual(basic.evidence.resistanceEvents,[]);const old=ability();old.spec={version:1,minimumNativeLevel:1,range:0,manaCost:2,accuracyModifier:0,damage:{type:'fire',min:10,max:10,penetration:2}};s.units[0]!.attackAbilities=[old];const result=use(s,20,{...rules,abilities:{version:1}});assert.equal(result.evidence.attack!.damage,0);assert.ok(!Object.hasOwn(result.evidence,'resistanceEvents'));});
test('unowned, unaffordable, wrong-side and stale counterplay cannot alter the caller state',()=>{for(const mutate of [(s:ReturnType<typeof initial>)=>{s.units[0]!.attackAbilities=[];},(s:ReturnType<typeof initial>)=>{s.units[0]!.mana=1;},(s:ReturnType<typeof initial>)=>{s.units[1]!.side='PARTY';}]){const s=initial();mutate(s);const before=structuredClone(s);assert.throws(()=>use(s));assert.deepEqual(s,before);}const s=initial();assert.throws(()=>stepTactical(rules,s,1,{actorId:'hero',kind:'END'}),/STALE/);});

test('damage-immunity bypass does not bypass matching status immunity on the connected hit',()=>{const r={...rules,roundEffects:{version:1 as const},statusDefense:{version:1 as const,tags:['burning']}},hero=unit('hero','PARTY',2),enemy=unit('enemy','ENEMY',1);hero.attackAbilities=[ability(0,true)];hero.onHitEffects=[{sourceId:'class.one',sourceRevision:2,effectId:'effect.burning',effectRevision:1,effect:{version:1,clock:'ROUNDS',tick:'OWNER_END',family:'burning',stacking:'REFRESH',rounds:2,polarity:'HARMFUL',tags:['burning'],modifiers:[{stat:'armor',amount:-1}]}}];enemy.damageProfile={version:1,attackType:'slashing',penetration:0,resistances:{fire:10000}};enemy.statusProfile={version:1,immuneTags:['burning']};const s=startTactical(r,[hero,enemy]),result=use(s,20,r);assert.equal(result.evidence.attack!.damage,8);assert.deepEqual(result.state.units[1]!.effects,[]);assert.equal(result.evidence.statusEvents!.length,1);});
