import test from 'node:test';
import assert from 'node:assert/strict';
import type pg from 'pg';
import { testDatabase } from './helpers.js';
import { tacticalPackage,tacticalFixture,envelope } from './tactical-fixture.js';
import { validateContent,publishContent } from '../src/domains/content.js';
import { startTacticalCombat,takeTacticalAction,tacticalView } from '../src/domains/tactical-combat.js';
import { integrityReport } from '../src/foundation/integrity.js';
import { setEquipment } from '../src/domains/equipment.js';
import type { TacticalCommand } from '../src/domains/tactical-encounters.js';
const json=(x:unknown)=>x as any;
const mechanics=(p:ReturnType<typeof tacticalPackage>,id:string)=>p.entities.find(e=>e.id===id)!.definition.mechanics!;
function familyPackage(){
 const p=tacticalPackage(),spec=json(mechanics(p,'encounter.tactical').tacticalCombat);spec.allies=[];spec.rules.typedDamage={version:2,types:['slashing','piercing','fire'],defaultType:'slashing',resistanceStacking:'SUM_CAPPED',families:{physical:['slashing','piercing'],elemental:['fire']}};spec.rules.abilities={version:1};spec.rules.roundEffects={version:2};
 for(const [id,bps,gate] of [['class.one',1000,1],['feat.vigor',2000,0],['item.shield',3000,0]] as const)mechanics(p,id).tacticalDamageTraits={version:1,minimumNativeLevel:gate,resistances:{physical:bps}};
 const monster=json(mechanics(p,'monster.tactical').tacticalUnit);monster.stats.maxHealth=100;monster.damageTraits={version:1,minimumNativeLevel:0,resistances:{physical:5000,elemental:5000}};
 mechanics(p,'class.one').tacticalAttackAbility={version:1,minimumNativeLevel:1,range:0,manaCost:2,accuracyModifier:0,damage:{type:'fire',min:12,max:12,penetration:0}};
 mechanics(p,'class.one').tacticalOnHitEffects={version:1,minimumNativeLevel:1,effectIds:['effect.burning']};p.entities.find(e=>e.id==='class.one')!.definition.dependencies.push('effect.burning');
 p.entities.push({id:'effect.burning',kind:'EFFECT',revision:1,schemaVersion:1,definition:{name:'Burning',dependencies:[],public:{},mechanics:{tacticalRoundEffect:{version:2,clock:'ROUNDS',tick:'OWNER_END',family:'burning',stacking:'REFRESH',rounds:2,polarity:'HARMFUL',tags:['burning'],modifiers:[],periodic:{kind:'DAMAGE',timing:'OWNER_END',amount:4,damageType:'fire',armor:'BYPASS',penetration:0}}}}});return p;
}
async function battle(pool:pg.Pool,f:Awaited<ReturnType<typeof tacticalFixture>>){let v=json(await startTacticalCombat(pool,f.account,envelope(f.revision,'START_TACTICAL'),'encounter.tactical'));return {get:()=>v,act:async(command:TacticalCommand)=>{v=json(await takeTacticalAction(pool,f.account,envelope(v.revision),v.instanceId,v.encounterRevision,v.tacticalRevision,command));return v;}};}
async function clean(pool:pg.Pool){assert.ok(Object.values(await integrityReport(pool)).every(n=>n===0));}
test('pinned family defenses execute basic, selected, enemy and periodic damage; concurrent retry/reconnect retains original memberships',async()=>{
 const db=await testDatabase();try{const p=familyPackage(),f=await tacticalFixture(db.pool,p),b=await battle(db.pool,f),v=b.get();
 const newer=structuredClone(p);newer.version='family-revision-two';for(const e of newer.entities)e.revision=2;const r=json(mechanics(newer,'encounter.tactical').tacticalCombat).rules.typedDamage;r.families.physical=['fire'];r.families.elemental=['slashing'];await publishContent(db.pool,newer);
 const request=envelope(v.revision),command={actorId:'hero',kind:'ATTACK' as const,targetId:'enemy'};const replies=await Promise.all([1,2,3].map(()=>takeTacticalAction(db.pool,f.account,request,v.instanceId,v.encounterRevision,v.tacticalRevision,command)));assert.equal(replies.filter(x=>!x.replayed).length,1);assert.equal(json(replies[0]).units[1].health,96);
 // Resume from the authoritative projection after the concurrent action.
 const resumed=json(await tacticalView(db.pool,f.account,v.instanceId));const end=async()=>takeTacticalAction(db.pool,f.account,envelope(resumed.revision),v.instanceId,resumed.encounterRevision,resumed.tacticalRevision,{actorId:'hero',kind:'END'});let next=json(await end());assert.equal(next.units[0].health,33);assert.equal(next.units[1].health,94);
 next=json(await takeTacticalAction(db.pool,f.account,envelope(next.revision),v.instanceId,next.encounterRevision,next.tacticalRevision,{actorId:'hero',kind:'USE_ABILITY',targetId:'enemy',abilityId:'class.one'}));assert.equal(next.units[1].health,88);assert.equal(next.units[0].mana,4);
 const rows=(await db.pool.query('SELECT intent,evidence FROM tactical_steps ORDER BY revision')).rows;const attacks=rows.filter(x=>x.evidence.attack);assert.deepEqual(attacks.map(x=>x.evidence.attack.afterResistance),[4,2,6]);const periodic=rows.flatMap(x=>x.evidence.periodicEvents??[]);assert.equal(periodic[0].resistanceBps,5000);assert.equal(periodic[0].amount,2);
 const origin=(await db.pool.query('SELECT initial_checkpoint FROM tactical_encounter_origins')).rows[0];assert.deepEqual(origin.initial_checkpoint.state.units[0].damageProfile.resistances,{slashing:6000,piercing:6000});assert.ok(!JSON.stringify(next).includes('sourceRevision'));await clean(db.pool);
 }finally{await db.close();}
});
test('native gates, unselected subclasses and inactive equipment do not contribute family defenses',async()=>{
 const db=await testDatabase();try{const p=familyPackage();json(mechanics(p,'class.one').tacticalDamageTraits).minimumNativeLevel=5;mechanics(p,'subclass.guard').tacticalDamageTraits={version:1,minimumNativeLevel:0,resistances:{physical:10000}};const f=await tacticalFixture(db.pool,p);await setEquipment(db.pool,f.account,envelope(f.revision,'SET_EQUIPMENT'),{activeSet:'B',slots:[{set:'A',slot:'MAIN_HAND',itemId:f.gear.sword!},{set:'A',slot:'OFF_HAND',itemId:f.gear.shield!}]});f.revision++;const b=await battle(db.pool,f);await b.act({actorId:'hero',kind:'END'});const e=(await db.pool.query("SELECT evidence FROM tactical_steps WHERE control='SERVER' AND intent->>'kind'='ATTACK'")).rows[0].evidence;assert.equal(e.attack.afterResistance,4);assert.equal(b.get().units[0].health,31);await clean(db.pool);}finally{await db.close();}
});
test('unknown owned family rejects start atomically even behind a native gate; creature and encounter membership errors reject publication',async()=>{
 const db=await testDatabase();try{const p=familyPackage();mechanics(p,'class.one').tacticalDamageTraits={version:1,minimumNativeLevel:5,resistances:{unknown:5000}};const f=await tacticalFixture(db.pool,p);await assert.rejects(startTacticalCombat(db.pool,f.account,envelope(f.revision,'START_TACTICAL'),'encounter.tactical'),/UNKNOWN/);assert.equal((await db.pool.query('SELECT count(*)::int n FROM tactical_encounter_origins')).rows[0].n,0);assert.equal((await db.pool.query('SELECT revision FROM runs WHERE id=$1',[f.run])).rows[0].revision,f.revision);await clean(db.pool);
 for(const mutate of [(p:ReturnType<typeof familyPackage>)=>{json(mechanics(p,'encounter.tactical').tacticalCombat).rules.typedDamage.families.physical=['unknown'];},(p:ReturnType<typeof familyPackage>)=>{json(mechanics(p,'monster.tactical').tacticalUnit).damageTraits.resistances={unknown:5000};},(p:ReturnType<typeof familyPackage>)=>{json(mechanics(p,'class.one').tacticalAttackAbility).damage.type='physical';},(p:ReturnType<typeof familyPackage>)=>{json(mechanics(p,'effect.burning').tacticalRoundEffect).periodic.damageType='elemental';}]){const bad=familyPackage();mutate(bad);if(json(mechanics(bad,'class.one').tacticalAttackAbility).damage.type==='physical'||json(mechanics(bad,'effect.burning').tacticalRoundEffect).periodic.damageType==='elemental'){const revision=json(mechanics(bad,'class.one').tacticalAttackAbility).damage.type==='physical'?2:3;bad.version=`invalid-family-offense-${revision}`;for(const e of bad.entities)e.revision=revision;const g=await tacticalFixture(db.pool,bad);await assert.rejects(startTacticalCombat(db.pool,g.account,envelope(g.revision,'START_TACTICAL'),'encounter.tactical'),/UNKNOWN|INVALID_TACTICAL_PERIODIC_DAMAGE/);}else assert.throws(()=>validateContent(bad));}
 }finally{await db.close();}
});
test('late action failure rolls back family-mitigated damage and draws; replay independently detects forged resolved defenses',async()=>{
 const db=await testDatabase();try{const f=await tacticalFixture(db.pool,familyPackage()),b=await battle(db.pool,f),v=b.get(),request=envelope(v.revision);await db.pool.query("CREATE FUNCTION fail_family() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Late family failure'; END $$; CREATE TRIGGER fail_family BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION fail_family()");const act=()=>takeTacticalAction(db.pool,f.account,request,v.instanceId,v.encounterRevision,v.tacticalRevision,{actorId:'hero',kind:'ATTACK',targetId:'enemy'});await assert.rejects(act(),/Late family failure/);assert.equal(json(await tacticalView(db.pool,f.account,v.instanceId)).units[1].health,100);assert.equal((await db.pool.query('SELECT count(*)::int n FROM tactical_steps')).rows[0].n,0);assert.equal((await db.pool.query("SELECT count(*)::int n FROM encounter_draws WHERE stream='tactical'")).rows[0].n,0);await db.pool.query('DROP TRIGGER fail_family ON audit_events');await act();assert.equal((await act()).replayed,true);await clean(db.pool);
 await assert.rejects(db.pool.query('UPDATE tactical_steps SET state=state'),/Immutable/);await db.pool.query('ALTER TABLE tactical_steps DISABLE TRIGGER tactical_step_immutable');await db.pool.query("UPDATE tactical_steps SET state=jsonb_set(state,'{units,1,damageProfile,resistances,slashing}','0'::jsonb)");await db.pool.query('ALTER TABLE tactical_steps ENABLE TRIGGER tactical_step_immutable');assert.ok((await integrityReport(db.pool)).tacticalMismatches>0);
 }finally{await db.close();}
});
