import test from 'node:test';
import assert from 'node:assert/strict';
import type pg from 'pg';
import { testDatabase } from './helpers.js';
import { tacticalPackage,tacticalFixture,envelope } from './tactical-fixture.js';
import { validateContent,publishContent } from '../src/domains/content.js';
import { startTacticalCombat,takeTacticalAction,tacticalView } from '../src/domains/tactical-combat.js';
import { integrityReport } from '../src/foundation/integrity.js';
import { setEquipment } from '../src/domains/equipment.js';
import { buildApp } from '../src/app.js';
import { enrollPassword,requireLogin } from '../src/auth/sessions.js';
import type { TacticalCommand } from '../src/domains/tactical-encounters.js';
const json=(x:unknown)=>x as any;
const mechanics=(p:ReturnType<typeof tacticalPackage>,id:string)=>p.entities.find(e=>e.id===id)!.definition.mechanics!;
const ability=(gate=1,reduction=4000,bypass=false)=>({version:2,minimumNativeLevel:gate,range:0,manaCost:2,accuracyModifier:0,damage:{type:'fire',min:12,max:12,penetration:0,resistanceReductionBps:reduction,bypassImmunity:bypass}});
function counterplayPackage(){const p=tacticalPackage(),spec=json(mechanics(p,'encounter.tactical').tacticalCombat);spec.allies=[];spec.rules.abilities={version:2};spec.rules.typedDamage={version:2,types:['slashing','fire'],defaultType:'slashing',resistanceStacking:'SUM_CAPPED',families:{elemental:['fire']}};const monster=json(mechanics(p,'monster.tactical').tacticalUnit);monster.stats.maxHealth=100;monster.stats.armor=2;monster.damageTraits={version:1,minimumNativeLevel:0,resistances:{elemental:6000}};mechanics(p,'class.one').tacticalAttackAbility=ability();mechanics(p,'item.sword').tacticalAttackAbility=ability(0,2500,true);return p;}
async function battle(pool:pg.Pool,f:Awaited<ReturnType<typeof tacticalFixture>>){let v=json(await startTacticalCombat(pool,f.account,envelope(f.revision,'START_TACTICAL'),'encounter.tactical'));return {get:()=>v,act:async(command:TacticalCommand)=>{v=json(await takeTacticalAction(pool,f.account,envelope(v.revision),v.instanceId,v.encounterRevision,v.tacticalRevision,command));return v;}};}
const use={actorId:'hero',kind:'USE_ABILITY' as const,targetId:'enemy',abilityId:'class.one'};
const clean=async(pool:pg.Pool)=>assert.ok(Object.values(await integrityReport(pool)).every(n=>n===0));
test('owned reduction and active-gear bypass retain pins/provenance through newer publication, concurrent retries and reconnect',async()=>{const db=await testDatabase();try{const p=counterplayPackage(),f=await tacticalFixture(db.pool,p),b=await battle(db.pool,f),v=b.get();assert.equal(v.partyCapabilities[0].attackAbilities[0].damage.resistanceReductionBps,4000);const newer=structuredClone(p);newer.version='counterplay-new';for(const e of newer.entities)e.revision=2;json(mechanics(newer,'class.one').tacticalAttackAbility).damage.resistanceReductionBps=10000;await publishContent(db.pool,newer);const request=envelope(v.revision),replies=await Promise.all([1,2,3].map(()=>takeTacticalAction(db.pool,f.account,request,v.instanceId,v.encounterRevision,v.tacticalRevision,use)));assert.equal(replies.filter(x=>!x.replayed).length,1);let next=json(await tacticalView(db.pool,f.account,v.instanceId));assert.equal(next.units[1].health,92);assert.equal(next.units[0].mana,4);next=json(await takeTacticalAction(db.pool,f.account,envelope(next.revision),v.instanceId,next.encounterRevision,next.tacticalRevision,{actorId:'hero',kind:'END'}));next=json(await takeTacticalAction(db.pool,f.account,envelope(next.revision),v.instanceId,next.encounterRevision,next.tacticalRevision,{...use,abilityId:'item.sword'}));assert.equal(next.units[1].health,86);assert.equal(next.units[0].mana,2);const evidence=(await db.pool.query("SELECT evidence FROM tactical_steps WHERE intent->>'kind'='USE_ABILITY' ORDER BY revision")).rows.map(r=>r.evidence);assert.deepEqual(evidence.map(e=>e.resistanceEvents[0].effectiveResistanceBps),[2000,3500]);assert.ok(evidence.every(e=>e.abilityEvents[0].sourceRevision===1));assert.deepEqual(evidence[1].abilityEvents[0].sourceInstanceIds,[f.gear.sword]);const defense=(await db.pool.query('SELECT initial_checkpoint FROM tactical_encounter_origins')).rows[0].initial_checkpoint.state.units[1].damageProfile;assert.equal(defense.resistances.fire,6000);assert.ok(!JSON.stringify(next).includes('resistanceEvents'));await clean(db.pool);}finally{await db.close();}});
test('reduction alone cannot pierce family immunity; explicit equipped bypass affects only its attack and not periodic/status rules',async()=>{const db=await testDatabase();try{const p=counterplayPackage();json(mechanics(p,'monster.tactical').tacticalUnit).damageTraits.resistances.elemental=10000;json(mechanics(p,'class.one').tacticalAttackAbility).damage.resistanceReductionBps=10000;json(mechanics(p,'encounter.tactical').tacticalCombat).rules.roundEffects={version:2};mechanics(p,'class.one').tacticalOnHitEffects={version:1,minimumNativeLevel:1,effectIds:['effect.burning']};for(const id of ['class.one'])p.entities.find(e=>e.id===id)!.definition.dependencies.push('effect.burning');p.entities.push({id:'effect.burning',kind:'EFFECT',revision:1,schemaVersion:1,definition:{name:'Burning',dependencies:[],public:{},mechanics:{tacticalRoundEffect:{version:2,clock:'ROUNDS',tick:'OWNER_END',family:'burning',stacking:'REFRESH',rounds:2,polarity:'HARMFUL',tags:['burning'],modifiers:[],periodic:{kind:'DAMAGE',timing:'OWNER_END',amount:4,damageType:'fire',armor:'BYPASS',penetration:0}}}}});const f=await tacticalFixture(db.pool,p),b=await battle(db.pool,f);await b.act(use);assert.equal(b.get().units[1].health,100);await b.act({actorId:'hero',kind:'END'});await b.act({...use,abilityId:'item.sword'});assert.equal(b.get().units[1].health,88);const e=(await db.pool.query("SELECT evidence FROM tactical_steps WHERE intent->>'abilityId'='item.sword'")).rows[0].evidence;assert.equal(e.resistanceEvents[0].bypassedImmunity,true);assert.equal(e.resistanceEvents[0].effectiveResistanceBps,-2500);assert.equal(e.attack.effectiveArmor,2);assert.equal(b.get().units[1].effects.length,1);await b.act({actorId:'hero',kind:'END'});await b.act({actorId:'hero',kind:'ATTACK',targetId:'enemy'});assert.deepEqual((await db.pool.query("SELECT evidence->'resistanceEvents' e FROM tactical_steps WHERE intent->>'actorId'='hero' AND intent->>'kind'='ATTACK'")).rows[0].e,[]);const pulses=(await db.pool.query('SELECT evidence FROM tactical_steps')).rows.flatMap(r=>r.evidence.periodicEvents??[]);assert.equal(pulses.length,2);assert.ok(pulses.every(e=>e.resistanceBps===10000&&e.amount===0));await clean(db.pool);}finally{await db.close();}});
test('server-controlled counterplay obeys costs and falls back after mana exhaustion; terminal recovery retains actual damage',async()=>{const db=await testDatabase();try{const p=counterplayPackage();mechanics(p,'class.one').tacticalDamageTraits={version:1,minimumNativeLevel:1,resistances:{elemental:10000}};const a=ability(0,2000,true);a.damage.penetration=1;a.damage.min=8;a.damage.max=8;mechanics(p,'monster.tactical').tacticalAttackAbility=a;const f=await tacticalFixture(db.pool,p),b=await battle(db.pool,f);for(let i=0;i<3;i++){await b.act({actorId:'hero',kind:'END'});assert.equal(b.get().units[0].health,35-7*(i+1));assert.equal(b.get().units[1].mana,4-2*i);}await b.act({actorId:'hero',kind:'END'});assert.equal(b.get().units[0].health,9);assert.equal((await db.pool.query("SELECT count(*)::int n FROM tactical_steps WHERE control='SERVER' AND intent->>'kind'='USE_ABILITY'")).rows[0].n,3);await b.act({actorId:'hero',kind:'RETREAT'});assert.equal(b.get().outcome,'RETREAT');assert.equal(b.get().recovery.health,9);await clean(db.pool);}finally{await db.close();}});
test('version opt-in, native gates, unselected sources and inactive gear block unauthorized counterplay',async()=>{const db=await testDatabase();try{const p=counterplayPackage();json(mechanics(p,'class.one').tacticalAttackAbility).minimumNativeLevel=5;mechanics(p,'subclass.guard').tacticalAttackAbility=ability(0);const f=await tacticalFixture(db.pool,p);await setEquipment(db.pool,f.account,envelope(f.revision,'SET_EQUIPMENT'),{activeSet:'B',slots:[{set:'A',slot:'MAIN_HAND',itemId:f.gear.sword!},{set:'A',slot:'OFF_HAND',itemId:f.gear.shield!}]});f.revision++;const b=await battle(db.pool,f);assert.deepEqual(b.get().partyCapabilities[0].attackAbilities,[]);for(const abilityId of ['class.one','subclass.guard','item.sword'])await assert.rejects(b.act({...use,abilityId}),/ILLEGAL/);assert.equal((await db.pool.query('SELECT count(*)::int n FROM tactical_steps')).rows[0].n,0);await clean(db.pool);const bad=counterplayPackage();json(mechanics(bad,'encounter.tactical').tacticalCombat).rules.abilities.version=1;mechanics(bad,'monster.tactical').tacticalAttackAbility=ability(0);assert.throws(()=>validateContent(bad),/DISABLED/);for(const damage of [{resistanceReductionBps:10001},{bypassImmunity:'yes'}]){const invalid=counterplayPackage();Object.assign(json(mechanics(invalid,'class.one').tacticalAttackAbility).damage,damage);assert.throws(()=>validateContent(invalid));}}finally{await db.close();}});
test('late failure rolls back counterplay damage/cost/draws and receipt; independent replay detects forged mitigation evidence',async()=>{const db=await testDatabase();try{const f=await tacticalFixture(db.pool,counterplayPackage()),b=await battle(db.pool,f),v=b.get(),request=envelope(v.revision);await db.pool.query("CREATE FUNCTION fail_counterplay() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Late counterplay failure'; END $$; CREATE TRIGGER fail_counterplay BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION fail_counterplay()");const act=()=>takeTacticalAction(db.pool,f.account,request,v.instanceId,v.encounterRevision,v.tacticalRevision,use);await assert.rejects(act(),/Late counterplay failure/);assert.equal(json(await tacticalView(db.pool,f.account,v.instanceId)).units[1].health,100);assert.equal((await db.pool.query('SELECT count(*)::int n FROM tactical_steps')).rows[0].n,0);assert.equal((await db.pool.query("SELECT count(*)::int n FROM encounter_draws WHERE stream='tactical'")).rows[0].n,0);assert.equal((await db.pool.query('SELECT count(*)::int n FROM action_receipts WHERE request_id=$1',[request.requestId])).rows[0].n,0);await db.pool.query('DROP TRIGGER fail_counterplay ON audit_events');await act();assert.equal((await act()).replayed,true);await clean(db.pool);await assert.rejects(db.pool.query('UPDATE tactical_steps SET evidence=evidence'),/Immutable/);await db.pool.query('ALTER TABLE tactical_steps DISABLE TRIGGER tactical_step_immutable');await db.pool.query("UPDATE tactical_steps SET evidence=jsonb_set(evidence,'{resistanceEvents,0,effectiveResistanceBps}','0'::jsonb)");await db.pool.query('ALTER TABLE tactical_steps ENABLE TRIGGER tactical_step_immutable');assert.ok((await integrityReport(db.pool)).tacticalMismatches>0);}finally{await db.close();}});
test('authenticated API accepts owned choices but rejects client counterplay parameters and enemy control',async()=>{const db=await testDatabase(),app=buildApp(db.pool,{mode:'sessions',throttleKey:'c'.repeat(64)});try{const f=await tacticalFixture(db.pool,counterplayPackage()),password='Counterplay test password 77!';await enrollPassword(db.pool,f.account,'counterplay_user',password);const login=await requireLogin(db.pool,'counterplay_user',password,'Counterplay'),headers={authorization:`Bearer ${login.token}`},b=await battle(db.pool,f),v=b.get(),payload={...envelope(v.revision),instanceId:v.instanceId,expectedEncounterRevision:v.encounterRevision,expectedTacticalRevision:v.tacticalRevision,command:use};for(const command of [{...use,resistanceReductionBps:10000},{...use,bypassImmunity:true},{...use,damage:{type:'fire',bypassImmunity:true}}])assert.equal((await app.inject({method:'POST',url:'/api/v1/tactical/actions',headers,payload:{...payload,command}})).statusCode,400);assert.equal((await app.inject({method:'POST',url:'/api/v1/tactical/actions',headers,payload:{...payload,command:{...use,actorId:'enemy'}}})).statusCode,403);const accepted=await app.inject({method:'POST',url:'/api/v1/tactical/actions',headers,payload});assert.equal(accepted.statusCode,200,accepted.body);assert.equal(accepted.json().units[1].health,92);assert.ok(!accepted.body.includes('resistanceEvents'));assert.ok(!accepted.body.includes('sourceRevision'));await clean(db.pool);}finally{await app.close();await db.close();}});
