import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import type pg from 'pg';
import { testDatabase } from './helpers.js';
import { tacticalPackage,tacticalFixture,envelope } from './tactical-fixture.js';
import { validateContent,publishContent } from '../src/domains/content.js';
import { startTacticalCombat,takeTacticalAction,tacticalView } from '../src/domains/tactical-combat.js';
import { integrityReport } from '../src/foundation/integrity.js';
import { setEquipment } from '../src/domains/equipment.js';
import { buildApp } from '../src/app.js';
import { enrollPassword,requireLogin } from '../src/auth/sessions.js';
import type { TacticalCommand } from '../src/domains/tactical-encounters.js';
const json=(v:unknown)=>v as any;
const projection=(v:any)=>{const {actionId,requestId,rulesVersion,replayed,...rest}=v;return rest;};
const traits=(minimumNativeLevel=0,immuneTags=['poison'])=>({version:1,minimumNativeLevel,immuneTags});
function statusPackage(){
 const p=tacticalPackage();p.version='status-fixture';const m=(id:string)=>p.entities.find(e=>e.id===id)!.definition.mechanics!,spec=json(m('encounter.tactical').tacticalCombat);spec.rules.roundEffects={version:3};spec.rules.statusDefense={version:1,tags:['poison','fear']};spec.rules.typedDamage={version:1,types:['fire','slashing'],defaultType:'slashing',resistanceStacking:'SUM_CAPPED'};spec.allies=[];json(m('monster.tactical').tacticalUnit).stats.maxHealth=100;
 p.entities.push({id:'effect.poisoned',kind:'EFFECT',revision:1,schemaVersion:1,definition:{name:'Test poison',dependencies:[],public:{},mechanics:{tacticalRoundEffect:{version:3,clock:'ROUNDS',tick:'OWNER_END',family:'poisoned',stacking:'REFRESH',rounds:3,polarity:'HARMFUL',tags:['poison','condition'],modifiers:[],periodic:{kind:'DAMAGE',timing:'OWNER_END',amount:6,damageType:'fire',armor:'BYPASS',penetration:0},removal:{method:'CURE',difficulty:4}}}}});
 m('item.shield').tacticalStatusTraits=traits();m('monster.tactical').tacticalOnHitEffects={version:1,minimumNativeLevel:0,effectIds:['effect.poisoned']};p.entities.find(e=>e.id==='monster.tactical')!.definition.dependencies.push('effect.poisoned');return p;
}
async function battle(pool:pg.Pool,f:any){let v=json(await startTacticalCombat(pool,f.account,envelope(f.revision,'START_TACTICAL'),'encounter.tactical'));return {get:()=>v,act:async(command:TacticalCommand)=>{v=json(await takeTacticalAction(pool,f.account,envelope(v.revision),v.instanceId,v.encounterRevision,v.tacticalRevision,command));return v;}};}
const clean=async(pool:pg.Pool)=>assert.ok(Object.values(await integrityReport(pool)).every(n=>n===0));
test('owned equipped immunity blocks enemy poison without blocking damage, pins publication and replays concurrent requests/reconnect',async()=>{
 const db=await testDatabase();try{const p=statusPackage(),f=await tacticalFixture(db.pool,p),b=await battle(db.pool,f),v=b.get();assert.deepEqual(v.partyCapabilities[0].statusImmunities,['poison']);const newer=structuredClone(p);newer.version='status-newer';for(const e of newer.entities)e.revision=2;newer.entities.find(e=>e.id==='item.shield')!.definition.mechanics!.tacticalStatusTraits=traits(0,['fear']);await publishContent(db.pool,newer);
 const request=envelope(v.revision),act=()=>takeTacticalAction(db.pool,f.account,request,v.instanceId,v.encounterRevision,v.tacticalRevision,{actorId:'hero',kind:'END'});const results=await Promise.all([act(),act(),act()]);assert.equal(results.filter(r=>!r.replayed).length,1);const after=json(results[0]);assert.equal(after.units[0].health,30);assert.deepEqual(after.units[0].effects,[]);assert.equal(after.units[0].mana,6);assert.deepEqual(after.partyCapabilities[0].statusImmunities,['poison']);assert.deepEqual(json(await tacticalView(db.pool,f.account,v.instanceId)),projection(after));assert.equal((await db.pool.query("SELECT count(*)::int n FROM encounter_draws WHERE stream='tactical'")).rows[0].n,2);
 const e=(await db.pool.query("SELECT evidence->'statusEvents'->0 e FROM tactical_steps WHERE intent->>'kind'='ATTACK'")).rows[0].e;assert.equal(e.kind,'IMMUNE');assert.deepEqual(e.matchedTags,['poison']);assert.equal(e.blocked.sourceId,'monster.tactical');assert.equal(e.blocked.sourceRevision,1);assert.equal(e.blocked.effectRevision,1);assert.equal(e.sourceUnitId,'enemy');assert.ok(!JSON.stringify(after).includes('statusEvents'));assert.ok(!JSON.stringify(after.units).includes('statusProfile'));await clean(db.pool);
 }finally{await db.close();}
});
test('creature immunity blocks owned class effects with full source evidence and allows normal enemy turns',async()=>{
 const db=await testDatabase();try{const p=statusPackage(),cls=p.entities.find(e=>e.id==='class.one')!,monster=p.entities.find(e=>e.id==='monster.tactical')!;cls.definition.mechanics!.tacticalOnHitEffects={version:1,minimumNativeLevel:1,effectIds:['effect.poisoned']};cls.definition.dependencies.push('effect.poisoned');monster.definition.mechanics!.tacticalStatusTraits=traits();const f=await tacticalFixture(db.pool,p),b=await battle(db.pool,f);await b.act({actorId:'hero',kind:'ATTACK',targetId:'enemy'});assert.equal(b.get().units[1].health,92);assert.deepEqual(b.get().units[1].effects,[]);await b.act({actorId:'hero',kind:'END'});assert.equal(b.get().units[0].health,30);const e=(await db.pool.query("SELECT evidence->'statusEvents'->0 e FROM tactical_steps WHERE control='PLAYER' AND intent->>'kind'='ATTACK'")).rows[0].e;assert.equal(e.blocked.sourceId,'class.one');assert.equal(e.blocked.sourceRevision,1);assert.equal(e.ownerId,'enemy');await clean(db.pool);
 }finally{await db.close();}
});
test('locked classes, unselected subclasses and inactive gear grant no immunity; matching damage resistance remains separate',async()=>{
 const db=await testDatabase();try{const p=statusPackage();p.entities.find(e=>e.id==='class.one')!.definition.mechanics!.tacticalStatusTraits=traits(5);p.entities.find(e=>e.id==='subclass.guard')!.definition.mechanics!.tacticalStatusTraits=traits();p.entities.find(e=>e.id==='feat.vigor')!.definition.mechanics!.tacticalDamageTraits={version:1,minimumNativeLevel:0,resistances:{fire:10000}};const f=await tacticalFixture(db.pool,p);await setEquipment(db.pool,f.account,envelope(f.revision,'SET_EQUIPMENT'),{activeSet:'B',slots:[{set:'A',slot:'MAIN_HAND',itemId:f.gear.sword!},{set:'A',slot:'OFF_HAND',itemId:f.gear.shield!}]});f.revision++;const b=await battle(db.pool,f);assert.deepEqual(b.get().partyCapabilities[0].statusImmunities,[]);await b.act({actorId:'hero',kind:'END'});assert.equal(b.get().units[0].effects.length,1);assert.equal(b.get().units[0].health,29);await b.act({actorId:'hero',kind:'END'});assert.equal(b.get().units[0].health,23);await clean(db.pool);
 }finally{await db.close();}
});
test('legacy unopted encounters ignore optional status traits and keep their original state/evidence shape',async()=>{
 const db=await testDatabase();try{const p=statusPackage();delete json(p.entities.find(e=>e.id==='encounter.tactical')!.definition.mechanics!.tacticalCombat).rules.statusDefense;const f=await tacticalFixture(db.pool,p),b=await battle(db.pool,f);assert.ok(!Object.hasOwn(b.get().partyCapabilities[0],'statusImmunities'));await b.act({actorId:'hero',kind:'END'});assert.equal(b.get().units[0].effects.length,1);const steps=(await db.pool.query('SELECT state,evidence FROM tactical_steps')).rows;for(const s of steps){assert.ok(!Object.hasOwn(s.evidence,'statusEvents'));assert.ok(s.state.units.every((u:any)=>!Object.hasOwn(u,'statusProfile')));}await clean(db.pool);
 }finally{await db.close();}
});
test('late immune application failure rolls back draws, state, journal and receipt; retry succeeds and audit detects forged immunity',async()=>{
 const db=await testDatabase();try{const f=await tacticalFixture(db.pool,statusPackage()),b=await battle(db.pool,f),before=b.get(),request=envelope(before.revision);await db.pool.query("CREATE FUNCTION fail_status() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Late status failure'; END $$; CREATE TRIGGER fail_status BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION fail_status()");const act=()=>takeTacticalAction(db.pool,f.account,request,before.instanceId,before.encounterRevision,before.tacticalRevision,{actorId:'hero',kind:'END'});await assert.rejects(act(),/Late status failure/);assert.deepEqual(json(await tacticalView(db.pool,f.account,before.instanceId)),projection(before));assert.equal((await db.pool.query('SELECT count(*)::int n FROM tactical_steps')).rows[0].n,0);assert.equal((await db.pool.query("SELECT count(*)::int n FROM encounter_draws WHERE stream='tactical'")).rows[0].n,0);assert.equal((await db.pool.query('SELECT count(*)::int n FROM action_receipts WHERE request_id=$1',[request.requestId])).rows[0].n,0);await db.pool.query('DROP TRIGGER fail_status ON audit_events');await act();assert.equal((await act()).replayed,true);await clean(db.pool);await assert.rejects(db.pool.query('UPDATE tactical_steps SET evidence=evidence'),/Immutable/);await db.pool.query('ALTER TABLE tactical_steps DISABLE TRIGGER tactical_step_immutable');await db.pool.query("UPDATE tactical_steps SET evidence=jsonb_set(evidence,'{statusEvents,0,blocked,sourceRevision}','999'::jsonb) WHERE intent->>'kind'='ATTACK'");await db.pool.query('ALTER TABLE tactical_steps ENABLE TRIGGER tactical_step_immutable');assert.ok((await integrityReport(db.pool)).tacticalMismatches>0);
 }finally{await db.close();}
});
test('publication and start reject unknown tags, invalid gates, unrelated sources and unsupported partial resistance',async()=>{
 const good=statusPackage();assert.doesNotThrow(()=>validateContent(good));for(const mutate of [(p:typeof good)=>{p.entities.find(e=>e.id==='item.ore')!.definition.mechanics!.tacticalStatusTraits=traits();},(p:typeof good)=>{p.entities.find(e=>e.id==='class.one')!.definition.mechanics!.tacticalStatusTraits=traits(100);},(p:typeof good)=>{p.entities.find(e=>e.id==='monster.tactical')!.definition.mechanics!.tacticalStatusTraits=traits(1);},(p:typeof good)=>{p.entities.find(e=>e.id==='monster.tactical')!.definition.mechanics!.tacticalStatusTraits=traits(0,['disease']);},(p:typeof good)=>{json(p.entities.find(e=>e.id==='item.shield')!.definition.mechanics!.tacticalStatusTraits).resistanceBps=5000;},(p:typeof good)=>{delete json(p.entities.find(e=>e.id==='encounter.tactical')!.definition.mechanics!.tacticalCombat).rules.roundEffects;}]){const p=structuredClone(good);mutate(p);assert.throws(()=>validateContent(p));}
 const db=await testDatabase();try{const p=statusPackage();p.entities.find(e=>e.id==='class.one')!.definition.mechanics!.tacticalStatusTraits=traits(5,['disease']);const f=await tacticalFixture(db.pool,p);await assert.rejects(startTacticalCombat(db.pool,f.account,envelope(f.revision,'START_TACTICAL'),'encounter.tactical'),/UNKNOWN_TACTICAL_STATUS_TAG/);assert.equal((await db.pool.query('SELECT count(*)::int n FROM instances')).rows[0].n,0);await clean(db.pool);}finally{await db.close();}
});
test('authenticated commands cannot inject immunities and owner projections keep enemy defenses/journal provenance private',async()=>{
 const db=await testDatabase(),app=buildApp(db.pool,{mode:'sessions',throttleKey:'s'.repeat(64)});try{const f=await tacticalFixture(db.pool,statusPackage()),password='Test status password 77!';await enrollPassword(db.pool,f.account,'status_user',password);const login=await requireLogin(db.pool,'status_user',password,'Status'),headers={authorization:`Bearer ${login.token}`},b=await battle(db.pool,f),v=b.get(),payload={...envelope(v.revision),instanceId:v.instanceId,expectedEncounterRevision:v.encounterRevision,expectedTacticalRevision:v.tacticalRevision,command:{actorId:'hero',kind:'END'}};for(const command of [{...payload.command,statusProfile:{version:1,immuneTags:['fear']}},{...payload.command,immuneTags:['fear']}])assert.equal((await app.inject({method:'POST',url:'/api/v1/tactical/actions',headers,payload:{...payload,command}})).statusCode,400);const reader=await requireLogin(db.pool,'status_user',password,'Reader',true);assert.equal((await app.inject({method:'POST',url:'/api/v1/tactical/actions',headers:{authorization:`Bearer ${reader.token}`},payload})).statusCode,403);const accepted=await app.inject({method:'POST',url:'/api/v1/tactical/actions',headers,payload});assert.equal(accepted.statusCode,200,accepted.body);assert.deepEqual(accepted.json().partyCapabilities[0].statusImmunities,['poison']);for(const key of ['statusProfile','statusEvents','sourceRevision','immuneTags'])assert.ok(!accepted.body.includes(key));await clean(db.pool);}finally{await app.close();await db.close();}
});
test('restricted runtime blocks effects and settles recovery using existing permissions',async()=>{
 const db=await testDatabase(),role=`status_${randomUUID().replaceAll('-','')}`;let created=false;try{const f=await tacticalFixture(db.pool,statusPackage());await db.pool.query(`CREATE ROLE ${role} NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS`);created=true;await db.pool.query(`GRANT USAGE ON SCHEMA ${db.schema} TO ${role}; GRANT SELECT ON ALL TABLES IN SCHEMA ${db.schema} TO ${role}; GRANT UPDATE(security_epoch) ON accounts TO ${role}; GRANT UPDATE ON runs,run_builds,run_progression,instances,state_scopes,inventory_containers,encounter_records,tactical_run_state,inventory_items TO ${role}; GRANT INSERT ON instances,instance_participants,state_scopes,encounter_records,encounter_draws,character_encounter_snapshots,encounter_reward_plans,encounter_reward_claims,encounter_reward_items,encounter_xp_plans,run_xp_awards,tactical_run_state,tactical_encounter_origins,tactical_steps,tactical_recoveries,action_receipts,turn_ledger,audit_events,outbox_events,inventory_items,inventory_quantity_operations TO ${role}; GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA ${db.schema} TO ${role}`);const client=await db.pool.connect();try{await client.query(`SET ROLE ${role}`);const pool={query:client.query.bind(client),connect:async()=>({query:client.query.bind(client),release:()=>{}})} as unknown as pg.Pool,b=await battle(pool,f);await b.act({actorId:'hero',kind:'END'});await b.act({actorId:'hero',kind:'RETREAT'});assert.equal(b.get().outcome,'RETREAT');assert.equal(b.get().recovery.health,30);assert.equal(b.get().recovery.mana,6);await assert.rejects(client.query('DELETE FROM tactical_steps'),e=>(e as {code:string}).code==='42501');}finally{await client.query('RESET ROLE');client.release();}await clean(db.pool);}finally{if(created){await db.pool.query(`DROP OWNED BY ${role}`);await db.pool.query(`DROP ROLE ${role}`);}await db.close();}
});
