import test from 'node:test';
import assert from 'node:assert/strict';
import { normalizeHealingAbilities,validateHealingAbility,type HealingAbility } from '../src/domains/tactical-healing-abilities.js';
import { startTactical,stepTactical,type TacticalRules,type TacticalUnit } from '../src/domains/tactical-engine.js';
const rules:TacticalRules={damage:{version:1,ruleset:'TACTICAL_DAMAGE_V1',check:{version:1,ruleset:'D20_CHECK_V1',attributeDivisor:2,attributeBaseline:10,proficiencyPerRank:2,natural20:'SUCCESS',natural1:'NORMAL'},criticalOn20:false,criticalMultiplierBps:20000,minimumConnectedDamage:1},zones:['floor','tower'],edges:[['floor','tower']],attackRange:0,healRange:0,healAmount:2,roundLimit:5,healManaCost:1,healingAbilities:{version:1}};
const ability=():HealingAbility=>({id:'class.one',sourceRevision:2,sourceInstanceIds:[],spec:{version:1,minimumNativeLevel:1,range:1,manaCost:2,min:8,max:10}});
const unit=(id:string,side:TacticalUnit['side'],initiative:number):TacticalUnit=>({id,side,zone:'floor',health:30,strikes:0,state:'ACTIVE',canHeal:false,stats:{maxHealth:30,maxMana:6,accuracy:20,evasion:10,armor:4,initiative,attackMin:3,attackMax:3}});
function initial(){const hero=unit('hero','PARTY',3),ally=unit('ally','PARTY',2);hero.healingAbilities=[ability()];ally.zone='tower';const s=startTactical(rules,[hero,ally,unit('enemy','ENEMY',1)]);s.units[1]!.health=20;return s;}
const heal=(s:ReturnType<typeof initial>,amount=10)=>stepTactical(rules,s,s.revision,{actorId:'hero',kind:'USE_HEALING_ABILITY',targetId:'ally',abilityId:'class.one',amount});
test('selected healing uses authored range/amount despite generic kit eligibility and records capped recovery/source costs',()=>{const s=initial(),before=structuredClone(s),result=heal(s);assert.deepEqual(s,before);assert.equal(result.state.units[1]!.health,30);assert.equal(result.state.units[0]!.mana,4);assert.equal(result.state.budgets.hero!.main,0);assert.equal(result.evidence.attack,null);assert.deepEqual(result.evidence.healingAbilityEvents,[{actorId:'hero',targetId:'ally',abilityId:'class.one',sourceRevision:2,sourceInstanceIds:[],manaCost:2,amount:10,healthBefore:20,healthAfter:30,stateBefore:'ACTIVE',stateAfter:'ACTIVE',strikesBefore:0,strikesAfter:0}]);assert.throws(()=>heal(result.state),/MAIN/);const capped=initial();capped.units[1]!.health=29;assert.equal(heal(capped).state.units[1]!.health,30);});
test('positive healing revives Downed allies and clears strikes without resurrecting Defeated targets',()=>{const s=initial();s.units[1]!.health=0;s.units[1]!.state='DOWNED';s.units[1]!.strikes=1;const result=heal(s,8);assert.equal(result.state.units[1]!.health,8);assert.equal(result.state.units[1]!.state,'ACTIVE');assert.equal(result.state.units[1]!.strikes,0);assert.equal(result.evidence.healingAbilityEvents![0]!.stateBefore,'DOWNED');s.units[1]!.state='DEFEATED';const before=structuredClone(s);assert.throws(()=>heal(s),/TARGET/);assert.deepEqual(s,before);});
test('full-health attempts still spend explicit resources; forged amounts, ownership, side, range and stale actions cannot mutate',()=>{const full=initial();full.units[1]!.health=30;assert.equal(heal(full).state.units[0]!.mana,4);for(const mutate of [(s:ReturnType<typeof initial>)=>{s.units[0]!.healingAbilities=[];},(s:ReturnType<typeof initial>)=>{s.units[0]!.mana=1;},(s:ReturnType<typeof initial>)=>{s.units[0]!.healingAbilities![0]!.spec.range=0;},(s:ReturnType<typeof initial>)=>{s.units[1]!.side='ENEMY';}]){const s=initial();mutate(s);const before=structuredClone(s);assert.throws(()=>heal(s));assert.deepEqual(s,before);}const s=initial();assert.throws(()=>heal(s,11));assert.throws(()=>heal(s,7));assert.throws(()=>stepTactical(rules,s,1,{actorId:'hero',kind:'END'}),/STALE/);});
test('duplicate equipped copies retain all instance identities without stacking healing or discounting cost',()=>{const a=ability(),b=ability();a.sourceInstanceIds=['11111111-1111-1111-1111-111111111111'];b.sourceInstanceIds=['22222222-2222-2222-2222-222222222222'];const list=normalizeHealingAbilities([a,b]);assert.deepEqual(list,normalizeHealingAbilities([b,a]));assert.equal(list.length,1);assert.equal(list[0]!.spec.min,8);assert.equal(list[0]!.sourceInstanceIds.length,2);b.spec.manaCost=1;assert.throws(()=>normalizeHealingAbilities([a,b]),/CONFLICTING/);});
test('healing definitions reject free or inverted magnitudes, unsupported revival promises and invalid bounds',()=>{for(const patch of [{manaCost:0},{min:0},{max:7},{range:32},{resurrect:true},{version:2}])assert.throws(()=>validateHealingAbility({...ability().spec,...patch}));const hero=unit('hero','PARTY',2);hero.healingAbilities=[ability()];const {healingAbilities,...old}=rules;assert.throws(()=>startTactical(old,[hero,unit('enemy','ENEMY',1)]),/DISABLED/);});
test('unopted encounters retain original generic healing and state/evidence shapes',()=>{const {healingAbilities,...old}=rules;const hero=unit('hero','PARTY',2);hero.canHeal=true;const s=startTactical(old,[hero,unit('enemy','ENEMY',1)]);s.units[0]!.health=20;assert.ok(!Object.hasOwn(s.units[0]!,'healingAbilities'));const result=stepTactical(old,s,0,{actorId:'hero',kind:'HEAL',targetId:'hero'});assert.equal(result.state.units[0]!.health,22);assert.equal(result.state.units[0]!.mana,5);assert.ok(!Object.hasOwn(result.evidence,'healingAbilityEvents'));});
