import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import type pg from 'pg';
import { testDatabase } from './helpers.js';
import { tacticalPackage,tacticalFixture,envelope } from './tactical-fixture.js';
import { validateContent,publishContent } from '../src/domains/content.js';
import { startTacticalCombat,takeTacticalAction,tacticalView } from '../src/domains/tactical-combat.js';
import { integrityReport } from '../src/foundation/integrity.js';
import { setEquipment } from '../src/domains/equipment.js';
import { buildApp } from '../src/app.js';
import { enrollPassword,requireLogin } from '../src/auth/sessions.js';
import type { TacticalCommand } from '../src/domains/tactical-encounters.js';
const json=(v:unknown)=>v as any;
const projection=(v:any)=>{const {actionId,requestId,rulesVersion,replayed,...rest}=v;return rest;};
const ability=(minimumNativeLevel=1,min=10,max=12)=>({version:1,minimumNativeLevel,range:1,manaCost:2,min,max});
function healingPackage(){const p=tacticalPackage();p.version='healing-ability-fixture';const m=(id:string)=>p.entities.find(e=>e.id===id)!.definition.mechanics!,spec=json(m('encounter.tactical').tacticalCombat);spec.rules.healingAbilities={version:1};spec.allies=[];json(m('monster.tactical').tacticalUnit).stats.maxHealth=100;m('class.one').tacticalHealingAbility=ability();return p;}
const heal={actorId:'hero',kind:'USE_HEALING_ABILITY' as const,targetId:'hero',abilityId:'class.one'};
async function battle(pool:pg.Pool,f:any){let v=json(await startTacticalCombat(pool,f.account,envelope(f.revision,'START_TACTICAL'),'encounter.tactical'));return {get:()=>v,act:async(command:TacticalCommand)=>{v=json(await takeTacticalAction(pool,f.account,envelope(v.revision),v.instanceId,v.encounterRevision,v.tacticalRevision,command));return v;}};}
const clean=async(pool:pg.Pool)=>assert.ok(Object.values(await integrityReport(pool)).every(n=>n===0));
test('owned class, selected feat and active gear heals pin sources, cap health and replay one draw/cost across concurrent retries and reconnect',async()=>{
 const db=await testDatabase();try{const p=healingPackage();p.entities.find(e=>e.id==='feat.vigor')!.definition.mechanics!.tacticalHealingAbility=ability(0,8,8);p.entities.find(e=>e.id==='item.shield')!.definition.mechanics!.tacticalHealingAbility=ability(0,9,9);const f=await tacticalFixture(db.pool,p),b=await battle(db.pool,f);await b.act({actorId:'hero',kind:'END'});assert.equal(b.get().units[0].health,30);const newer=structuredClone(p);newer.version='healing-ability-newer';for(const e of newer.entities)e.revision=2;newer.entities.find(e=>e.id==='item.shield')!.definition.mechanics!.tacticalHealingAbility=ability(0,99,99);await publishContent(db.pool,newer);const v=b.get(),request=envelope(v.revision),act=()=>takeTacticalAction(db.pool,f.account,request,v.instanceId,v.encounterRevision,v.tacticalRevision,heal);const results=await Promise.all([act(),act(),act()]);assert.equal(results.filter(r=>!r.replayed).length,1);const after=json(results[0]);assert.equal(after.units[0].health,35);assert.equal(after.units[0].mana,4);assert.deepEqual(json(await tacticalView(db.pool,f.account,v.instanceId)),projection(after));await assert.rejects(takeTacticalAction(db.pool,f.account,envelope(after.revision),v.instanceId,after.encounterRevision,after.tacticalRevision,heal),/MAIN/);
 const next=json(await takeTacticalAction(db.pool,f.account,envelope(after.revision),v.instanceId,after.encounterRevision,after.tacticalRevision,{actorId:'hero',kind:'END'}));const gear=json(await takeTacticalAction(db.pool,f.account,envelope(next.revision),v.instanceId,next.encounterRevision,next.tacticalRevision,{...heal,abilityId:'item.shield'}));assert.equal(gear.units[0].mana,2);assert.equal(gear.partyCapabilities[0].healingAbilities.find((a:any)=>a.abilityId==='item.shield').max,9);const again=json(await takeTacticalAction(db.pool,f.account,envelope(gear.revision),v.instanceId,gear.encounterRevision,gear.tacticalRevision,{actorId:'hero',kind:'END'}));await takeTacticalAction(db.pool,f.account,envelope(again.revision),v.instanceId,again.encounterRevision,again.tacticalRevision,{...heal,abilityId:'feat.vigor'});
 const events=(await db.pool.query("SELECT evidence->'healingAbilityEvents'->0 e FROM tactical_steps WHERE intent->>'kind'='USE_HEALING_ABILITY' ORDER BY revision")).rows.map(r=>r.e);assert.deepEqual(events.map(e=>e.abilityId),['class.one','item.shield','feat.vigor']);assert.ok(events.every(e=>e.sourceRevision===1));assert.deepEqual(events[1].sourceInstanceIds,[f.gear.shield]);assert.ok(events[0].amount>=10&&events[0].amount<=12);assert.equal(events[0].healthAfter-events[0].healthBefore,5);assert.equal((await db.pool.query("SELECT count(*)::int n FROM encounter_draws WHERE stream='tactical' AND draw_key LIKE '%.healing'")).rows[0].n,3);await clean(db.pool);
 }finally{await db.close();}
});
test('owned healing revives a real Downed ally, restores its turn and triggers pinned on-heal HoT without resurrecting or ticking early',async()=>{
 const db=await testDatabase();try{const p=healingPackage(),spec=json(p.entities.find(e=>e.id==='encounter.tactical')!.definition.mechanics!.tacticalCombat);spec.allies=[{id:'ally',definitionId:'npc.ally',zone:'floor'}];spec.rules.roundEffects={version:2};const enemy=json(p.entities.find(e=>e.id==='monster.tactical')!.definition.mechanics!.tacticalUnit);enemy.stats.attackMin=enemy.stats.attackMax=21;json(p.entities.find(e=>e.id==='npc.ally')!.definition.mechanics!.tacticalUnit).stats.armor=0;const cls=p.entities.find(e=>e.id==='class.one')!;cls.definition.mechanics!.tacticalHealingAbility=ability(1,10,10);cls.definition.mechanics!.tacticalOnHealEffects={version:1,minimumNativeLevel:1,effectIds:['effect.regrowth']};cls.definition.dependencies.push('effect.regrowth');p.entities.push({id:'effect.regrowth',kind:'EFFECT',revision:1,schemaVersion:1,definition:{name:'Test regrowth',dependencies:[],public:{},mechanics:{tacticalRoundEffect:{version:2,clock:'ROUNDS',tick:'OWNER_END',family:'regrowth',stacking:'REFRESH',rounds:3,polarity:'BENEFICIAL',tags:['regrowth'],modifiers:[],periodic:{kind:'HEAL',timing:'OWNER_START',amount:2}}}}});const f=await tacticalFixture(db.pool,p),b=await battle(db.pool,f);await b.act({actorId:'hero',kind:'END'});await b.act({actorId:'ally',kind:'END'});assert.equal(b.get().units[1].state,'DOWNED');await b.act({...heal,targetId:'ally'});assert.equal(b.get().units[1].health,10);assert.equal(b.get().units[1].state,'ACTIVE');assert.equal(b.get().units[1].strikes,0);const e=(await db.pool.query("SELECT evidence FROM tactical_steps WHERE intent->>'kind'='USE_HEALING_ABILITY'")).rows[0].evidence;assert.equal(e.healingAbilityEvents[0].stateBefore,'DOWNED');assert.deepEqual(e.periodicEvents,[]);await b.act({actorId:'hero',kind:'END'});assert.equal(b.get().currentActor,'ally');assert.equal(b.get().units[1].health,12);await clean(db.pool);
 }finally{await db.close();}
});
test('server self-healing obeys Main/mana, journals one healing draw and falls back to attack after resource exhaustion',async()=>{
 const db=await testDatabase();try{const p=healingPackage(),m=p.entities.find(e=>e.id==='monster.tactical')!.definition.mechanics!;json(m.tacticalUnit).stats.maxHealth=40;m.tacticalHealingAbility=ability(0,5,5);const f=await tacticalFixture(db.pool,p),b=await battle(db.pool,f);for(let i=0;i<3;i++){await b.act({actorId:'hero',kind:'ATTACK',targetId:'enemy'});await b.act({actorId:'hero',kind:'END'});assert.equal(b.get().units[0].health,35);assert.equal(b.get().units[1].mana,4-2*i);}await b.act({actorId:'hero',kind:'ATTACK',targetId:'enemy'});await b.act({actorId:'hero',kind:'END'});assert.equal(b.get().units[0].health,30);assert.equal((await db.pool.query("SELECT count(*)::int n FROM tactical_steps WHERE control='SERVER' AND intent->>'kind'='USE_HEALING_ABILITY'")).rows[0].n,3);assert.equal((await db.pool.query("SELECT count(*)::int n FROM tactical_steps WHERE control='SERVER' AND intent->>'kind'='ATTACK'")).rows[0].n,1);await clean(db.pool);
 }finally{await db.close();}
});
test('locked classes, unselected subclasses and inactive gear grant no healing and cannot fabricate draws or costs',async()=>{
 const db=await testDatabase();try{const p=healingPackage();p.entities.find(e=>e.id==='class.one')!.definition.mechanics!.tacticalHealingAbility=ability(5);p.entities.find(e=>e.id==='subclass.guard')!.definition.mechanics!.tacticalHealingAbility=ability(0);p.entities.find(e=>e.id==='item.shield')!.definition.mechanics!.tacticalHealingAbility=ability(0);const f=await tacticalFixture(db.pool,p);await setEquipment(db.pool,f.account,envelope(f.revision,'SET_EQUIPMENT'),{activeSet:'B',slots:[{set:'A',slot:'MAIN_HAND',itemId:f.gear.sword!},{set:'A',slot:'OFF_HAND',itemId:f.gear.shield!}]});f.revision++;const b=await battle(db.pool,f);assert.deepEqual(b.get().partyCapabilities[0].healingAbilities,[]);for(const abilityId of ['class.one','subclass.guard','item.shield'])await assert.rejects(b.act({...heal,abilityId}),/ILLEGAL/);await assert.rejects(b.act({...heal,targetId:'enemy'}),/ILLEGAL/);assert.equal((await db.pool.query('SELECT count(*)::int n FROM tactical_steps')).rows[0].n,0);assert.equal((await db.pool.query("SELECT count(*)::int n FROM encounter_draws WHERE stream='tactical'")).rows[0].n,0);await clean(db.pool);
 }finally{await db.close();}
});
test('publication rejects unrelated/free/inverted/unreachable healing; unopted history keeps generic healing and original shape',async()=>{
 const good=healingPackage();assert.doesNotThrow(()=>validateContent(good));for(const mutate of [(p:typeof good)=>{p.entities.find(e=>e.id==='item.ore')!.definition.mechanics!.tacticalHealingAbility=ability(0);},(p:typeof good)=>{p.entities.find(e=>e.id==='monster.tactical')!.definition.mechanics!.tacticalHealingAbility=ability(1);},(p:typeof good)=>{p.entities.find(e=>e.id==='class.one')!.definition.mechanics!.tacticalHealingAbility=ability(100);},(p:typeof good)=>{json(p.entities.find(e=>e.id==='class.one')!.definition.mechanics!.tacticalHealingAbility).manaCost=0;},(p:typeof good)=>{json(p.entities.find(e=>e.id==='class.one')!.definition.mechanics!.tacticalHealingAbility).max=9;},(p:typeof good)=>{json(p.entities.find(e=>e.id==='class.one')!.definition.mechanics!.tacticalHealingAbility).resurrect=true;}]){const p=structuredClone(good);mutate(p);assert.throws(()=>validateContent(p));}
 const db=await testDatabase();try{const p=healingPackage();delete json(p.entities.find(e=>e.id==='encounter.tactical')!.definition.mechanics!.tacticalCombat).rules.healingAbilities;const f=await tacticalFixture(db.pool,p),b=await battle(db.pool,f);assert.ok(!Object.hasOwn(b.get().partyCapabilities[0],'healingAbilities'));await b.act({actorId:'hero',kind:'END'});await b.act({actorId:'hero',kind:'HEAL',targetId:'hero'});assert.equal(b.get().units[0].health,35);assert.equal(b.get().units[0].mana,4);for(const row of (await db.pool.query('SELECT state,evidence FROM tactical_steps')).rows){assert.ok(!Object.hasOwn(row.evidence,'healingAbilityEvents'));assert.ok(row.state.units.every((u:any)=>!Object.hasOwn(u,'healingAbilities')));}await clean(db.pool);}finally{await db.close();}
});
test('late heal failure rolls back health/mana/Main/draws/history and receipt; retry replays and independent audit detects forged provenance',async()=>{
 const db=await testDatabase();try{const f=await tacticalFixture(db.pool,healingPackage()),b=await battle(db.pool,f);await b.act({actorId:'hero',kind:'END'});const v=b.get(),request=envelope(v.revision),count=(await db.pool.query('SELECT count(*)::int n FROM tactical_steps')).rows[0].n;await db.pool.query("CREATE FUNCTION fail_healing_ability() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Late healing ability failure'; END $$; CREATE TRIGGER fail_healing_ability BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION fail_healing_ability()");const act=()=>takeTacticalAction(db.pool,f.account,request,v.instanceId,v.encounterRevision,v.tacticalRevision,heal);await assert.rejects(act(),/Late healing ability failure/);assert.deepEqual(json(await tacticalView(db.pool,f.account,v.instanceId)),projection(v));assert.equal((await db.pool.query('SELECT count(*)::int n FROM tactical_steps')).rows[0].n,count);assert.equal((await db.pool.query("SELECT count(*)::int n FROM encounter_draws WHERE stream='tactical' AND draw_key LIKE '%.healing'")).rows[0].n,0);assert.equal((await db.pool.query('SELECT count(*)::int n FROM action_receipts WHERE request_id=$1',[request.requestId])).rows[0].n,0);await db.pool.query('DROP TRIGGER fail_healing_ability ON audit_events');assert.equal(json(await act()).units[0].mana,4);assert.equal((await act()).replayed,true);await clean(db.pool);await assert.rejects(db.pool.query('UPDATE tactical_steps SET evidence=evidence'),/Immutable/);await db.pool.query('ALTER TABLE tactical_steps DISABLE TRIGGER tactical_step_immutable');await db.pool.query("UPDATE tactical_steps SET evidence=jsonb_set(evidence,'{healingAbilityEvents,0,sourceRevision}','999'::jsonb) WHERE intent->>'kind'='USE_HEALING_ABILITY'");await db.pool.query('ALTER TABLE tactical_steps ENABLE TRIGGER tactical_step_immutable');assert.ok((await integrityReport(db.pool)).tacticalMismatches>0);
 }finally{await db.close();}
});
test('authenticated healing API accepts owned target choices while rejecting forged amount/cost, enemy control and read-only writes',async()=>{
 const db=await testDatabase(),app=buildApp(db.pool,{mode:'sessions',throttleKey:'h'.repeat(64)});try{const f=await tacticalFixture(db.pool,healingPackage()),password='Test healing password 77!';await enrollPassword(db.pool,f.account,'healing_user',password);const login=await requireLogin(db.pool,'healing_user',password,'Healing'),headers={authorization:`Bearer ${login.token}`},b=await battle(db.pool,f),v=b.get(),payload={...envelope(v.revision),instanceId:v.instanceId,expectedEncounterRevision:v.encounterRevision,expectedTacticalRevision:v.tacticalRevision,command:heal};for(const command of [{...heal,amount:999},{...heal,manaCost:0},{...heal,resurrect:true}])assert.equal((await app.inject({method:'POST',url:'/api/v1/tactical/actions',headers,payload:{...payload,command}})).statusCode,400);assert.equal((await app.inject({method:'POST',url:'/api/v1/tactical/actions',headers,payload:{...payload,command:{...heal,actorId:'enemy'}}})).statusCode,403);const reader=await requireLogin(db.pool,'healing_user',password,'Reader',true);assert.equal((await app.inject({method:'POST',url:'/api/v1/tactical/actions',headers:{authorization:`Bearer ${reader.token}`},payload})).statusCode,403);const accepted=await app.inject({method:'POST',url:'/api/v1/tactical/actions',headers,payload});assert.equal(accepted.statusCode,200,accepted.body);assert.equal(accepted.json().units[0].mana,4);for(const key of ['sourceRevision','sourceInstanceIds','healingAbilityEvents'])assert.ok(!accepted.body.includes(key));await clean(db.pool);}finally{await app.close();await db.close();}
});
test('restricted runtime uses healing and settles retained pools; a subsequent encounter preserves spent mana',async()=>{
 const db=await testDatabase(),role=`healing_${randomUUID().replaceAll('-','')}`;let created=false;try{const f=await tacticalFixture(db.pool,healingPackage());await db.pool.query(`CREATE ROLE ${role} NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS`);created=true;await db.pool.query(`GRANT USAGE ON SCHEMA ${db.schema} TO ${role}; GRANT SELECT ON ALL TABLES IN SCHEMA ${db.schema} TO ${role}; GRANT UPDATE(security_epoch) ON accounts TO ${role}; GRANT UPDATE ON runs,run_builds,run_progression,instances,state_scopes,inventory_containers,encounter_records,tactical_run_state,inventory_items TO ${role}; GRANT INSERT ON instances,instance_participants,state_scopes,encounter_records,encounter_draws,character_encounter_snapshots,encounter_reward_plans,encounter_reward_claims,encounter_reward_items,encounter_xp_plans,run_xp_awards,tactical_run_state,tactical_encounter_origins,tactical_steps,tactical_recoveries,action_receipts,turn_ledger,audit_events,outbox_events,inventory_items,inventory_quantity_operations TO ${role}; GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA ${db.schema} TO ${role}`);const client=await db.pool.connect();try{await client.query(`SET ROLE ${role}`);const pool={query:client.query.bind(client),connect:async()=>({query:client.query.bind(client),release:()=>{}})} as unknown as pg.Pool,b=await battle(pool,f);await b.act({actorId:'hero',kind:'END'});await b.act(heal);await b.act({actorId:'hero',kind:'END'});await b.act({actorId:'hero',kind:'RETREAT'});assert.equal(b.get().outcome,'RETREAT');assert.equal(b.get().recovery.mana,4);assert.equal(b.get().recovery.health,30);const next=json(await startTacticalCombat(pool,f.account,envelope(b.get().revision,'START_TACTICAL'),'encounter.tactical'));assert.equal(next.units[0].mana,4);assert.equal(next.units[0].health,30);await assert.rejects(client.query('DELETE FROM tactical_steps'),e=>(e as {code:string}).code==='42501');}finally{await client.query('RESET ROLE');client.release();}await clean(db.pool);}finally{if(created){await db.pool.query(`DROP OWNED BY ${role}`);await db.pool.query(`DROP ROLE ${role}`);}await db.close();}
});
