import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import type pg from 'pg';
import { testDatabase } from './helpers.js';
import { tacticalPackage,tacticalFixture,envelope } from './tactical-fixture.js';
import { validateContent,publishContent } from '../src/domains/content.js';
import { startTacticalCombat,takeTacticalAction,tacticalView } from '../src/domains/tactical-combat.js';
import { integrityReport } from '../src/foundation/integrity.js';
import { setEquipment } from '../src/domains/equipment.js';
import { buildApp } from '../src/app.js';
import { enrollPassword,requireLogin } from '../src/auth/sessions.js';
import type { TacticalCommand } from '../src/domains/tactical-encounters.js';
const json=(v:unknown)=>v as any;
const projection=(v:any)=>{const {actionId,requestId,rulesVersion,replayed,...rest}=v;return rest;};
const ability=(minimumNativeLevel=1)=>({version:1,minimumNativeLevel,range:1,manaCost:2,accuracyModifier:1,damage:{type:'fire',min:12,max:12,penetration:2}});
function abilityPackage(){const p=tacticalPackage();p.version='ability-fixture';const m=(id:string)=>p.entities.find(e=>e.id===id)!.definition.mechanics!,spec=json(m('encounter.tactical').tacticalCombat);spec.rules.abilities={version:1};spec.rules.typedDamage={version:1,types:['fire','slashing'],defaultType:'slashing',resistanceStacking:'SUM_CAPPED'};spec.allies=[];json(m('monster.tactical').tacticalUnit).stats.maxHealth=100;json(m('monster.tactical').tacticalUnit).stats.armor=4;json(m('monster.tactical').tacticalUnit).damageTraits={version:1,minimumNativeLevel:0,resistances:{fire:5000}};m('class.one').tacticalAttackAbility=ability();return p;}
const use={actorId:'hero',kind:'USE_ABILITY' as const,targetId:'enemy',abilityId:'class.one'};
async function battle(pool:pg.Pool,f:any){let v=json(await startTacticalCombat(pool,f.account,envelope(f.revision,'START_TACTICAL'),'encounter.tactical'));return {get:()=>v,act:async(command:TacticalCommand)=>{v=json(await takeTacticalAction(pool,f.account,envelope(v.revision),v.instanceId,v.encounterRevision,v.tacticalRevision,command));return v;}};}
const clean=async(pool:pg.Pool)=>assert.ok(Object.values(await integrityReport(pool)).every(n=>n===0));
test('owned class, selected feat and active weapon abilities execute with their own ranges/costs and pinned source/instance provenance',async()=>{
 const db=await testDatabase();try{const p=abilityPackage(),m=(id:string)=>p.entities.find(e=>e.id===id)!.definition.mechanics!;m('feat.vigor').tacticalAttackAbility=ability(0);m('item.sword').tacticalAttackAbility=ability(0);json(m('encounter.tactical').tacticalCombat).enemies[0].zone='balcony';const f=await tacticalFixture(db.pool,p),b=await battle(db.pool,f);assert.equal(b.get().partyCapabilities[0].attackAbilities.length,3);await assert.rejects(b.act({actorId:'hero',kind:'ATTACK',targetId:'enemy'}),/ILLEGAL/);await b.act(use);assert.equal(b.get().units[1].health,95);assert.equal(b.get().units[0].mana,4);await assert.rejects(b.act(use),/MAIN/);
 const newer=structuredClone(p);newer.version='ability-fixture-newer';for(const e of newer.entities)e.revision=2;json(newer.entities.find(e=>e.id==='item.sword')!.definition.mechanics!.tacticalAttackAbility).damage.min=99;json(newer.entities.find(e=>e.id==='item.sword')!.definition.mechanics!.tacticalAttackAbility).damage.max=99;await publishContent(db.pool,newer);await b.act({actorId:'hero',kind:'END'});await b.act({...use,abilityId:'item.sword'});assert.equal(b.get().units[1].health,90);assert.equal(b.get().units[0].mana,2);await b.act({actorId:'hero',kind:'END'});await b.act({...use,abilityId:'feat.vigor'});assert.equal(b.get().units[1].health,85);assert.equal(b.get().units[0].mana,0);assert.deepEqual(json(await tacticalView(db.pool,f.account,b.get().instanceId)),projection(b.get()));
 const events=(await db.pool.query("SELECT evidence->'abilityEvents'->0 e FROM tactical_steps WHERE intent->>'kind'='USE_ABILITY' ORDER BY revision")).rows.map(r=>r.e);assert.deepEqual(events.map(e=>e.abilityId),['class.one','item.sword','feat.vigor']);assert.ok(events.every(e=>e.sourceRevision===1));assert.deepEqual(events[1].sourceInstanceIds,[f.gear.sword]);assert.equal((await db.pool.query("SELECT count(*)::int n FROM encounter_draws WHERE stream='tactical' AND draw_key LIKE '%.damage'")).rows[0].n,5);await clean(db.pool);
 }finally{await db.close();}
});
test('server creature abilities obey mana/Main and range with independently replayed decisions and defeat recovery',async()=>{
 const db=await testDatabase();try{const p=abilityPackage(),m=p.entities.find(e=>e.id==='monster.tactical')!.definition.mechanics!;m.tacticalAttackAbility={...ability(0),damage:{type:'fire',min:12,max:12,penetration:4}};const f=await tacticalFixture(db.pool,p),b=await battle(db.pool,f);await b.act({actorId:'hero',kind:'END'});assert.equal(b.get().units[0].health,23);assert.equal(b.get().units[1].mana,4);await b.act({actorId:'hero',kind:'END'});assert.equal(b.get().units[0].health,11);await b.act({actorId:'hero',kind:'END'});assert.equal(b.get().outcome,'DEFEAT');assert.equal(b.get().recovery.health,5);assert.equal(b.get().recovery.mana,6);assert.equal((await db.pool.query("SELECT count(*)::int n FROM tactical_steps WHERE control='SERVER' AND intent->>'kind'='USE_ABILITY'")).rows[0].n,3);await clean(db.pool);
 }finally{await db.close();}
});
test('ability victory settles once under concurrent retries and retains spent mana for the next encounter',async()=>{
 const db=await testDatabase();try{const p=abilityPackage(),t=json(p.entities.find(e=>e.id==='monster.tactical')!.definition.mechanics!.tacticalUnit);t.stats.maxHealth=5;const f=await tacticalFixture(db.pool,p),b=await battle(db.pool,f),v=b.get(),request=envelope(v.revision),act=()=>takeTacticalAction(db.pool,f.account,request,v.instanceId,v.encounterRevision,v.tacticalRevision,use);const results=await Promise.all([act(),act(),act()]);assert.equal(results.filter(r=>!r.replayed).length,1);const after=json(results[0]);assert.equal(after.outcome,'VICTORY');assert.equal(after.recovery.mana,4);assert.equal((await db.pool.query("SELECT count(*)::int n FROM encounter_draws WHERE stream='tactical'")).rows[0].n,2);assert.equal((await db.pool.query('SELECT count(*)::int n FROM run_xp_awards')).rows[0].n,1);assert.equal((await db.pool.query('SELECT count(*)::int n FROM encounter_reward_claims')).rows[0].n,1);const next=json(await startTacticalCombat(db.pool,f.account,envelope(after.revision,'START_TACTICAL'),'encounter.tactical'));assert.equal(next.units[0].mana,4);await clean(db.pool);
 }finally{await db.close();}
});
test('native gates, unselected subclasses and inactive gear do not grant abilities; strict publication/start rejects invalid sources and vocabulary',async()=>{
 const good=abilityPackage();for(const mutate of [(p:typeof good)=>{p.entities.find(e=>e.id==='item.ore')!.definition.mechanics!.tacticalAttackAbility=ability(0);},(p:typeof good)=>{p.entities.find(e=>e.id==='monster.tactical')!.definition.mechanics!.tacticalAttackAbility=ability(1);},(p:typeof good)=>{json(p.entities.find(e=>e.id==='class.one')!.definition.mechanics!.tacticalAttackAbility).manaCost=0;},(p:typeof good)=>{json(p.entities.find(e=>e.id==='class.one')!.definition.mechanics!.tacticalAttackAbility).minimumNativeLevel=100;},(p:typeof good)=>{delete json(p.entities.find(e=>e.id==='encounter.tactical')!.definition.mechanics!.tacticalCombat).rules.typedDamage;}]){const p=structuredClone(good);mutate(p);assert.throws(()=>validateContent(p));}
 const db=await testDatabase();try{const p=abilityPackage();p.entities.find(e=>e.id==='class.one')!.definition.mechanics!.tacticalAttackAbility=ability(5);p.entities.find(e=>e.id==='subclass.guard')!.definition.mechanics!.tacticalAttackAbility=ability(0);p.entities.find(e=>e.id==='item.sword')!.definition.mechanics!.tacticalAttackAbility=ability(0);const f=await tacticalFixture(db.pool,p);await setEquipment(db.pool,f.account,envelope(f.revision,'SET_EQUIPMENT'),{activeSet:'B',slots:[{set:'A',slot:'MAIN_HAND',itemId:f.gear.sword!},{set:'A',slot:'OFF_HAND',itemId:f.gear.shield!}]});f.revision++;const b=await battle(db.pool,f);assert.deepEqual(b.get().partyCapabilities[0].attackAbilities,[]);for(const abilityId of ['class.one','subclass.guard','item.sword'])await assert.rejects(b.act({...use,abilityId}),/ILLEGAL/);assert.equal((await db.pool.query('SELECT count(*)::int n FROM tactical_steps')).rows[0].n,0);assert.equal((await db.pool.query("SELECT count(*)::int n FROM encounter_draws WHERE stream='tactical'")).rows[0].n,0);await clean(db.pool);}finally{await db.close();}
 const invalid=await testDatabase();try{const p=abilityPackage();json(p.entities.find(e=>e.id==='class.one')!.definition.mechanics!.tacticalAttackAbility).damage.type='void';const f=await tacticalFixture(invalid.pool,p);await assert.rejects(startTacticalCombat(invalid.pool,f.account,envelope(f.revision,'START_TACTICAL'),'encounter.tactical'),/UNKNOWN/);assert.equal((await invalid.pool.query('SELECT count(*)::int n FROM instances')).rows[0].n,0);}finally{await invalid.close();}
});
test('connected zero-damage abilities retain generic on-hit grants and typed status immunity counterplay',async()=>{
 const db=await testDatabase();try{const p=abilityPackage(),cls=p.entities.find(e=>e.id==='class.one')!,monster=p.entities.find(e=>e.id==='monster.tactical')!,spec=json(p.entities.find(e=>e.id==='encounter.tactical')!.definition.mechanics!.tacticalCombat);spec.rules.roundEffects={version:3};spec.rules.statusDefense={version:1,tags:['poison']};json(monster.definition.mechanics!.tacticalUnit).damageTraits.resistances.fire=10000;monster.definition.mechanics!.tacticalStatusTraits={version:1,minimumNativeLevel:0,immuneTags:['poison']};p.entities.push({id:'effect.poisoned',kind:'EFFECT',revision:1,schemaVersion:1,definition:{name:'Test poison',dependencies:[],public:{},mechanics:{tacticalRoundEffect:{version:3,clock:'ROUNDS',tick:'OWNER_END',family:'poisoned',stacking:'REFRESH',rounds:3,polarity:'HARMFUL',tags:['poison'],modifiers:[{stat:'accuracy',amount:-4}],removal:{method:'CURE',difficulty:4}}}}});cls.definition.mechanics!.tacticalOnHitEffects={version:1,minimumNativeLevel:1,effectIds:['effect.poisoned']};cls.definition.dependencies.push('effect.poisoned');const f=await tacticalFixture(db.pool,p),b=await battle(db.pool,f);await b.act(use);assert.equal(b.get().units[1].health,100);assert.deepEqual(b.get().units[1].effects,[]);const e=(await db.pool.query("SELECT evidence FROM tactical_steps WHERE intent->>'kind'='USE_ABILITY'")).rows[0].evidence;assert.equal(e.attack.check.success,true);assert.equal(e.statusEvents[0].blocked.sourceId,'class.one');assert.equal(e.abilityEvents[0].manaCost,2);await clean(db.pool);
 }finally{await db.close();}
});
test('late ability failure rolls back draws/mana/Main/journal and receipt; retry replays and audit detects forged ability evidence',async()=>{
 const db=await testDatabase();try{const f=await tacticalFixture(db.pool,abilityPackage()),b=await battle(db.pool,f),v=b.get(),request=envelope(v.revision);await db.pool.query("CREATE FUNCTION fail_ability() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Late ability failure'; END $$; CREATE TRIGGER fail_ability BEFORE INSERT ON audit_events FOR EACH ROW EXECUTE FUNCTION fail_ability()");const act=()=>takeTacticalAction(db.pool,f.account,request,v.instanceId,v.encounterRevision,v.tacticalRevision,use);await assert.rejects(act(),/Late ability failure/);assert.deepEqual(json(await tacticalView(db.pool,f.account,v.instanceId)),projection(v));assert.equal((await db.pool.query('SELECT count(*)::int n FROM tactical_steps')).rows[0].n,0);assert.equal((await db.pool.query("SELECT count(*)::int n FROM encounter_draws WHERE stream='tactical'")).rows[0].n,0);assert.equal((await db.pool.query('SELECT count(*)::int n FROM action_receipts WHERE request_id=$1',[request.requestId])).rows[0].n,0);await db.pool.query('DROP TRIGGER fail_ability ON audit_events');assert.equal(json(await act()).units[0].mana,4);assert.equal((await act()).replayed,true);await clean(db.pool);await assert.rejects(db.pool.query('UPDATE tactical_steps SET evidence=evidence'),/Immutable/);await db.pool.query('ALTER TABLE tactical_steps DISABLE TRIGGER tactical_step_immutable');await db.pool.query("UPDATE tactical_steps SET evidence=jsonb_set(evidence,'{abilityEvents,0,sourceRevision}','999'::jsonb)");await db.pool.query('ALTER TABLE tactical_steps ENABLE TRIGGER tactical_step_immutable');assert.ok((await integrityReport(db.pool)).tacticalMismatches>0);
 }finally{await db.close();}
});
test('authenticated ability API accepts owned choices while rejecting forged magnitudes/rolls/costs, enemy control and read-only writes',async()=>{
 const db=await testDatabase(),app=buildApp(db.pool,{mode:'sessions',throttleKey:'a'.repeat(64)});try{const f=await tacticalFixture(db.pool,abilityPackage()),password='Test ability password 77!';await enrollPassword(db.pool,f.account,'ability_user',password);const login=await requireLogin(db.pool,'ability_user',password,'Ability'),headers={authorization:`Bearer ${login.token}`},b=await battle(db.pool,f),v=b.get(),payload={...envelope(v.revision),instanceId:v.instanceId,expectedEncounterRevision:v.encounterRevision,expectedTacticalRevision:v.tacticalRevision,command:use};for(const command of [{...use,roll:20},{...use,rawDamage:999},{...use,manaCost:0},{...use,damageType:'void'}])assert.equal((await app.inject({method:'POST',url:'/api/v1/tactical/actions',headers,payload:{...payload,command}})).statusCode,400);assert.equal((await app.inject({method:'POST',url:'/api/v1/tactical/actions',headers,payload:{...payload,command:{...use,actorId:'enemy'}}})).statusCode,403);const reader=await requireLogin(db.pool,'ability_user',password,'Reader',true);assert.equal((await app.inject({method:'POST',url:'/api/v1/tactical/actions',headers:{authorization:`Bearer ${reader.token}`},payload})).statusCode,403);const accepted=await app.inject({method:'POST',url:'/api/v1/tactical/actions',headers,payload});assert.equal(accepted.statusCode,200,accepted.body);assert.equal(accepted.json().units[0].mana,4);for(const key of ['sourceRevision','sourceInstanceIds','abilityEvents'])assert.ok(!accepted.body.includes(key));await clean(db.pool);}finally{await app.close();await db.close();}
});
test('restricted runtime executes authored abilities and terminal recovery with existing permissions',async()=>{
 const db=await testDatabase(),role=`ability_${randomUUID().replaceAll('-','')}`;let created=false;try{const f=await tacticalFixture(db.pool,abilityPackage());await db.pool.query(`CREATE ROLE ${role} NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS`);created=true;await db.pool.query(`GRANT USAGE ON SCHEMA ${db.schema} TO ${role}; GRANT SELECT ON ALL TABLES IN SCHEMA ${db.schema} TO ${role}; GRANT UPDATE(security_epoch) ON accounts TO ${role}; GRANT UPDATE ON runs,run_builds,run_progression,instances,state_scopes,inventory_containers,encounter_records,tactical_run_state,inventory_items TO ${role}; GRANT INSERT ON instances,instance_participants,state_scopes,encounter_records,encounter_draws,character_encounter_snapshots,encounter_reward_plans,encounter_reward_claims,encounter_reward_items,encounter_xp_plans,run_xp_awards,tactical_run_state,tactical_encounter_origins,tactical_steps,tactical_recoveries,action_receipts,turn_ledger,audit_events,outbox_events,inventory_items,inventory_quantity_operations TO ${role}; GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA ${db.schema} TO ${role}`);const client=await db.pool.connect();try{await client.query(`SET ROLE ${role}`);const pool={query:client.query.bind(client),connect:async()=>({query:client.query.bind(client),release:()=>{}})} as unknown as pg.Pool,b=await battle(pool,f);await b.act(use);await b.act({actorId:'hero',kind:'END'});await b.act({actorId:'hero',kind:'RETREAT'});assert.equal(b.get().outcome,'RETREAT');assert.equal(b.get().recovery.mana,4);await assert.rejects(client.query('DELETE FROM tactical_steps'),e=>(e as {code:string}).code==='42501');}finally{await client.query('RESET ROLE');client.release();}await clean(db.pool);}finally{if(created){await db.pool.query(`DROP OWNED BY ${role}`);await db.pool.query(`DROP ROLE ${role}`);}await db.close();}
});
