import test from 'node:test';
import assert from 'node:assert/strict';
import { deriveStatusProfile,validateStatusTraits } from '../src/domains/tactical-status.js';
import { startTactical,stepTactical,validateTacticalRules,type TacticalRules,type TacticalUnit } from '../src/domains/tactical-engine.js';
import type { EffectGrant } from '../src/domains/tactical-effects.js';
const rules:TacticalRules={damage:{version:1,ruleset:'TACTICAL_DAMAGE_V1',check:{version:1,ruleset:'D20_CHECK_V1',attributeDivisor:2,attributeBaseline:10,proficiencyPerRank:2,natural20:'SUCCESS',natural1:'NORMAL'},criticalOn20:false,criticalMultiplierBps:20000,minimumConnectedDamage:1},zones:['floor'],edges:[],attackRange:0,healRange:0,healAmount:2,roundLimit:5,roundEffects:{version:3},statusDefense:{version:1,tags:['poison','fear']}};
const traits=(immuneTags=['poison'],minimumNativeLevel=0)=>({version:1 as const,minimumNativeLevel,immuneTags});
const grant=(polarity:EffectGrant['effect']['polarity']='HARMFUL',tags=['poison']):EffectGrant=>({effectId:'effect.poison',effectRevision:2,sourceId:'class.one',sourceRevision:3,effect:{version:3,clock:'ROUNDS',tick:'OWNER_END',family:'poison',stacking:'REFRESH',rounds:3,polarity,tags,modifiers:[{stat:'accuracy',amount:-4}],removal:{method:'CURE',difficulty:2}}});
const unit=(id:string,side:TacticalUnit['side'],initiative:number):TacticalUnit=>({id,side,zone:'floor',health:20,strikes:0,state:'ACTIVE',stats:{maxHealth:20,maxMana:6,accuracy:20,evasion:10,armor:0,initiative,attackMin:3,attackMax:3}});
const attack=(s:ReturnType<typeof startTactical>)=>stepTactical(rules,s,0,{actorId:'hero',kind:'ATTACK',targetId:'enemy',roll:10,rawDamage:3});
function fight(g=grant()){const hero=unit('hero','PARTY',2),enemy=unit('enemy','ENEMY',1);hero.onHitEffects=[g];enemy.statusProfile={version:1,immuneTags:['poison']};return startTactical(rules,[hero,enemy]);}
test('explicit status tags union without power stacking; native gates and unknown locked tags remain authoritative',()=>{
 const r=rules.statusDefense!,sources=[{traits:traits(),nativeLevel:0},{traits:traits(['fear'],2),nativeLevel:1},{traits:traits(),nativeLevel:0}];assert.deepEqual(deriveStatusProfile(r,sources),{version:1,immuneTags:['poison']});sources[1]!.nativeLevel=2;assert.deepEqual(deriveStatusProfile(r,sources),deriveStatusProfile(r,sources.reverse()));assert.deepEqual(deriveStatusProfile(r,[]),{version:1,immuneTags:[]});assert.throws(()=>deriveStatusProfile(r,[{traits:traits(['disease'],5),nativeLevel:0}]),/UNKNOWN/);
});
test('matching harmful and mixed effects are blocked with complete incoming provenance, while damage still lands',()=>{
 for(const polarity of ['HARMFUL','MIXED'] as const){const s=fight(grant(polarity)),before=structuredClone(s),result=attack(s);assert.deepEqual(s,before);assert.equal(result.state.units[1]!.health,17);assert.deepEqual(result.state.units[1]!.effects,[]);assert.deepEqual(result.evidence.effectEvents,[]);assert.deepEqual(result.evidence.statusEvents,[{kind:'IMMUNE',ownerId:'enemy',sourceUnitId:'hero',matchedTags:['poison'],blocked:grant(polarity)}]);assert.equal(result.state.budgets.hero!.main,0);}
});
test('beneficial/neutral effects and unmatched tags still apply; damage immunity does not imply status immunity',()=>{
 for(const g of [grant('BENEFICIAL'),grant('NEUTRAL'),grant('HARMFUL',['fear'])]){const result=attack(fight(g));assert.equal(result.state.units[1]!.effects!.length,1);assert.deepEqual(result.evidence.statusEvents,[]);}
 const r={...rules,typedDamage:{version:1 as const,types:['fire'],defaultType:'fire',resistanceStacking:'SUM_CAPPED' as const}},hero=unit('hero','PARTY',2),enemy=unit('enemy','ENEMY',1);hero.onHitEffects=[grant()];enemy.damageProfile={version:1,attackType:'fire',penetration:0,resistances:{fire:10000}};const s=startTactical(r,[hero,enemy]),result=stepTactical(r,s,0,{actorId:'hero',kind:'ATTACK',targetId:'enemy',roll:10,rawDamage:3});assert.equal(result.state.units[1]!.health,20);assert.equal(result.state.units[1]!.effects!.length,1);
});
test('on-heal harmful tags use the same defense without blocking healing or benign grants',()=>{
 const hero=unit('hero','PARTY',2),ally=unit('ally','PARTY',1);ally.health=10;ally.statusProfile={version:1,immuneTags:['poison']};hero.onHealEffects=[grant()];const s=startTactical(rules,[hero,ally,unit('enemy','ENEMY',0)]),result=stepTactical(rules,s,0,{actorId:'hero',kind:'HEAL',targetId:'ally'});assert.equal(result.state.units[1]!.health,12);assert.deepEqual(result.state.units[1]!.effects,[]);assert.equal(result.evidence.statusEvents!.length,1);
});
test('unopted versions retain original shape and applications; rejected/stale actions cannot fabricate immunity evidence',()=>{
 const {statusDefense,...r}=rules;const hero=unit('hero','PARTY',2);hero.onHitEffects=[grant()];const s=startTactical(r,[hero,unit('enemy','ENEMY',1)]);assert.ok(!Object.hasOwn(s.units[0]!,'statusProfile'));const result=stepTactical(r,s,0,{actorId:'hero',kind:'ATTACK',targetId:'enemy',roll:10,rawDamage:3});assert.ok(!Object.hasOwn(result.evidence,'statusEvents'));assert.equal(result.state.units[1]!.effects!.length,1);const guarded=fight(),before=structuredClone(guarded);assert.throws(()=>stepTactical(rules,guarded,1,{actorId:'hero',kind:'END'}),/STALE/);assert.deepEqual(guarded,before);
});
test('strict opt-in/profile/source contracts reject unsupported partial resistance, malformed tags and hidden defaults',()=>{
 for(const patch of [{immuneTags:[]},{immuneTags:['poison','poison']},{immuneTags:['Bad Tag']},{minimumNativeLevel:-1},{resistanceBps:5000},{version:2}])assert.throws(()=>validateStatusTraits({...traits(),...patch}));assert.throws(()=>validateTacticalRules({...rules,roundEffects:undefined}));assert.throws(()=>validateTacticalRules({...rules,statusDefense:{version:1,tags:[]}}));const hero=unit('hero','PARTY',2);hero.statusProfile={version:1,immuneTags:['disease']};assert.throws(()=>startTactical(rules,[hero,unit('enemy','ENEMY',1)]),/INVALID/);hero.statusProfile={version:1,immuneTags:['poison']};const {statusDefense,...old}=rules;assert.throws(()=>startTactical(old,[hero,unit('enemy','ENEMY',1)]),/DISABLED/);
});
