import test from 'node:test';
import assert from 'node:assert/strict';
import { attributes,type StartingAttributes } from '../src/domains/build-content.js';
import { startTactical,stepTactical,type TacticalRules,type TacticalUnit } from '../src/domains/tactical-engine.js';
import { techniqueProfile,validateTechniquePack,type TechniquePack,type TechniqueSpec } from '../src/domains/tactical-techniques.js';
const rules:TacticalRules={techniques:{version:1},typedDamage:{version:1,types:['fire'],defaultType:'fire',resistanceStacking:'SUM_CAPPED'},damage:{version:1,ruleset:'TACTICAL_DAMAGE_V1',check:{version:1,ruleset:'D20_CHECK_V1',attributeBaseline:10,attributeDivisor:2,proficiencyPerRank:2,natural1:'NORMAL',natural20:'NORMAL'},criticalOn20:false,criticalMultiplierBps:20000,minimumConnectedDamage:0},zones:['floor','balcony'],edges:[['floor','balcony']],attackRange:0,healRange:1,healAmount:5,roundLimit:10};
const scores=Object.fromEntries(attributes.map(a=>[a,14])) as StartingAttributes;
const ability=(changes:Partial<TechniqueSpec>={}):TechniqueSpec=>({key:'wave',minimumNativeLevel:1,action:'MAIN',targetSide:'ENEMY',range:1,area:'ZONE',manaCost:2,resourceCost:{focus:1},cooldownRounds:1,check:{mode:'ATTACK',attribute:'intelligence',skillId:'skill.magic',difficulty:10,modifier:0},effect:{kind:'DAMAGE',type:'fire',min:8,max:8,penetration:1},...changes});
const profile=(abilities=[ability()])=>techniqueProfile({id:'class.mage',kind:'CLASS',revision:1,schemaVersion:1,definition:{name:'Mage',dependencies:[],public:{}}},{version:1,resources:[{key:'focus',maximum:2,clock:'ENCOUNTER'}],abilities},new Map([['effect.control',{id:'effect.control',kind:'EFFECT',revision:1,schemaVersion:1,definition:{name:'Control',dependencies:[],public:{},mechanics:{tacticalRoundEffect:control('ROOT',4) as any}}}]]));
function unit(id:string,side:TacticalUnit['side'],initiative:number):TacticalUnit{return {id,side,zone:'floor',health:20,strikes:0,state:'ACTIVE',canHeal:false,stats:{maxHealth:20,maxMana:8,accuracy:0,evasion:12,armor:1,initiative,attackMin:4,attackMax:4},checkAttributes:structuredClone(scores),checkSkills:{'skill.magic':2}};}
function initial(abilities=[ability()]){const hero=unit('hero','PARTY',4);hero.techniques=profile(abilities);return startTactical(rules,[hero,unit('ally','PARTY',3),unit('enemy','ENEMY',2),unit('enemy.other','ENEMY',1)]);}
const use={kind:'TECHNIQUE' as const,actorId:'hero',targetId:'enemy',abilityId:'class.mage.wave',draws:[{targetId:'enemy',roll:6,amount:8},{targetId:'enemy.other',roll:6,amount:8}]};
test('area targeting applies once per eligible target with independent checks and a single action/resource spend',()=>{const s=initial(),result=stepTactical(rules,s,0,use);assert.equal(result.state.units[0]!.mana,6);assert.equal(result.state.units[0]!.techniqueResources!['class.mage.focus'],1);assert.equal(result.state.budgets.hero!.main,0);assert.deepEqual(result.state.units.map(u=>u.health),[20,20,12,12]);assert.deepEqual(result.evidence.technique!.events.map(e=>[e.check!.attribute,e.check!.proficiency]),[[2,4],[2,4]]);assert.equal(result.state.units[0]!.techniqueCooldowns!['class.mage.wave'],3);assert.equal(s.units[0]!.mana,8);assert.deepEqual(stepTactical(rules,s,0,result.evidence.intent),result);});
test('range, area draw identities, costs and cooldown legality reject without mutating inputs',()=>{for(const mutate of [(s:ReturnType<typeof initial>)=>{s.units[0]!.mana=1;},(s:ReturnType<typeof initial>)=>{s.units[0]!.techniqueResources!['class.mage.focus']=0;},(s:ReturnType<typeof initial>)=>{s.units[0]!.techniqueCooldowns!['class.mage.wave']=2;}]){const s=initial();mutate(s);const copy=structuredClone(s);assert.throws(()=>stepTactical(rules,s,0,use),/ILLEGAL_TACTICAL_TECHNIQUE/);assert.deepEqual(s,copy);}const s=initial();assert.throws(()=>stepTactical(rules,s,0,{...use,draws:[...use.draws].reverse()}),/DRAWS/);assert.throws(()=>stepTactical(rules,s,0,{...use,targetId:'ally'}),/TARGET/);assert.throws(()=>stepTactical(rules,s,0,{...use,draws:[{targetId:'enemy',roll:20,amount:999},{targetId:'enemy.other',roll:20,amount:8}]}),/DRAWS/);});
test('selected attacks observe Guard and matching typed defense',()=>{const s=initial();s.units[2]!.guardReady=true;s.units[2]!.canGuard=true;s.units[2]!.damageProfile={version:1,attackType:'fire',penetration:0,resistances:{fire:5000}};const result=stepTactical({...rules,guardArmorBonus:3},s,0,use);assert.equal(result.evidence.technique!.events[0]!.damage!.damage,2);assert.equal(result.state.budgets.enemy!.reaction,0);assert.equal(result.state.units[3]!.health,12);});
test('stabilization protects one escalation, consumes its own Main action and never revives; resurrection restores a Defeated ally for a finite resource',()=>{const s=initial([ability({key:'stabilize',targetSide:'ALLY',area:'SINGLE',effect:{kind:'STABILIZE'},check:undefined}),ability({key:'resurrect',targetSide:'ALLY',area:'SINGLE',effect:{kind:'RESURRECT',min:4,max:4},check:undefined})]);s.units[1]!.state='DOWNED';s.units[1]!.health=0;const stable=stepTactical(rules,s,0,{kind:'TECHNIQUE',actorId:'hero',targetId:'ally',abilityId:'class.mage.stabilize',draws:[{targetId:'ally'}]}).state;assert.equal(stable.units[1]!.state,'DOWNED');assert.equal(stable.units[1]!.stabilized,true);stable.cursor=2;const hit=stepTactical(rules,stable,1,{kind:'ATTACK',actorId:'enemy',targetId:'ally',roll:20,rawDamage:4}).state;assert.equal(hit.units[1]!.strikes,0);assert.equal(hit.units[1]!.stabilized,false);const dead=initial([ability({key:'resurrect',targetSide:'ALLY',area:'SINGLE',effect:{kind:'RESURRECT',min:4,max:4},check:undefined})]);dead.units[1]!.state='DEFEATED';dead.units[1]!.health=0;const revived=stepTactical(rules,dead,0,{kind:'TECHNIQUE',actorId:'hero',targetId:'ally',abilityId:'class.mage.resurrect',draws:[{targetId:'ally',amount:4}]}).state;assert.equal(revived.units[1]!.state,'ACTIVE');assert.equal(revived.units[1]!.health,4);assert.equal(revived.units[0]!.techniqueResources!['class.mage.focus'],1);});
test('strict authoring rejects duplicate abilities, unknown resources, free resurrection and incompatible checks',()=>{const pack:TechniquePack={version:1,resources:[{key:'focus',maximum:2,clock:'ENCOUNTER'}],abilities:[ability()]};for(const bad of [{...pack,abilities:[ability(),ability()]},{...pack,resources:[]},{...pack,abilities:[ability({effect:{kind:'RESURRECT',min:2,max:1},targetSide:'ALLY',check:undefined})]},{...pack,abilities:[ability({effect:{kind:'RESURRECT',min:2,max:2},targetSide:'ALLY',check:undefined,manaCost:0,resourceCost:{}})]},{...pack,clientPower:99}])assert.throws(()=>validateTechniquePack(bad));});

import { deriveStatusProfile } from '../src/domains/tactical-status.js';
import { applyOnHitEffects,decayBuildups,validateRoundEffect,type RoundEffect,type EffectGrant } from '../src/domains/tactical-effects.js';
const control=(kind:'ROOT'|'DISARM'|'SILENCE'|'REACTION_LOCK'|'STUN'|'DAZED'='STUN',rounds=1):RoundEffect=>({version:4,clock:'ROUNDS',tick:'OWNER_END',family:'control',stacking:'REPLACE',rounds,polarity:'HARMFUL',tags:['control'],modifiers:[],removal:{method:'CLEANSE',difficulty:1},control:kind});
const grant=(effect:RoundEffect):EffectGrant=>({effectId:'effect.control',effectRevision:1,sourceId:'class.mage',sourceRevision:1,effect});
const controlledRules={...rules,roundEffects:{version:4 as const},statusDefense:{version:2 as const,tags:['control']}};
test('stun ends a turn legally, root blocks movement, disarm blocks attacks, and reaction suppression cannot spend Guard',()=>{for(const [kind,intent,error] of [['STUN',{actorId:'hero',kind:'ATTACK',targetId:'enemy',roll:20,rawDamage:4},'STUNNED'],['ROOT',{actorId:'hero',kind:'MOVE',zone:'balcony'},'ROOTED'],['DISARM',{actorId:'hero',kind:'ATTACK',targetId:'enemy',roll:20,rawDamage:4},'DISARMED']] as const){const s=startTactical(controlledRules,[unit('hero','PARTY',3),unit('enemy','ENEMY',2)]);applyOnHitEffects(s.units[0]!,{id:'enemy',onHitEffects:[grant(control(kind))]},0,[]);const before=structuredClone(s);assert.throws(()=>stepTactical(controlledRules,s,0,intent),new RegExp(error));assert.deepEqual(s,before);const ended=stepTactical(controlledRules,s,0,{actorId:'hero',kind:'END'});assert.equal(ended.state.units[0]!.effects!.length,0);assert.equal(ended.state.order[ended.state.cursor],'enemy');}const s=startTactical({...controlledRules,guardArmorBonus:5},[unit('hero','PARTY',2),unit('enemy','ENEMY',3)]);s.units[0]!.canGuard=true;s.units[0]!.guardReady=true;applyOnHitEffects(s.units[0]!,{id:'enemy',onHitEffects:[grant(control('REACTION_LOCK'))]},0,[]);const hit=stepTactical({...controlledRules,guardArmorBonus:5},s,0,{actorId:'enemy',kind:'ATTACK',targetId:'hero',roll:20,rawDamage:4});assert.equal(hit.evidence.attack!.effectiveArmor,1);assert.equal(hit.state.budgets.hero!.reaction,1);});
test('partial condition defense reduces a declared duration, while full tag immunity blocks it and remains distinct from damage defense',()=>{const owner={id:'enemy',effects:[],statusProfile:deriveStatusProfile(controlledRules.statusDefense,[{nativeLevel:0,traits:{version:2,minimumNativeLevel:0,immuneTags:[],durationReductionBps:{control:5000}}}])};const events:any[]=[];applyOnHitEffects(owner,{id:'hero',onHitEffects:[grant(control('ROOT',4))]},1,events);assert.equal(json(owner.effects)[0].remaining,2);assert.equal(events[0].kind,'RESISTED');const immune={id:'enemy',effects:[],statusProfile:deriveStatusProfile(controlledRules.statusDefense,[{nativeLevel:0,traits:{version:2,minimumNativeLevel:0,immuneTags:['control'],durationReductionBps:{}}}])};applyOnHitEffects(immune,{id:'hero',onHitEffects:[grant(control())]},1,events);assert.equal(immune.effects.length,0);assert.equal(events.at(-1).kind,'IMMUNE');assert.throws(()=>validateRoundEffect(control('STUN',3)),/CONTROL/);});
const json=(v:unknown)=>v as any;
test('buildup decays, converts at its threshold, discards overflow and raises subsequent break thresholds',()=>{const effect={...control(),buildup:{amount:6,threshold:10,decay:1,repeatedThresholdStep:5}} as RoundEffect,owner:TacticalUnit={...unit('enemy','ENEMY',1),effects:[],buildups:{}};const source={id:'hero',onHitEffects:[grant(effect)]};assert.equal(applyOnHitEffects(owner,source,1)[0]!.kind,'BUILT_UP');assert.equal(owner.effects!.length,0);assert.equal(owner.buildups!.control!.value,6);decayBuildups(owner);assert.equal(owner.buildups!.control!.value,5);const applied=applyOnHitEffects(owner,source,2);assert.equal(applied.at(-1)!.kind,'APPLIED');assert.equal(owner.buildups!.control!.value,0);assert.equal(owner.buildups!.control!.breaks,1);applyOnHitEffects(owner,source,3);assert.equal(owner.buildups!.control!.threshold,15);assert.equal(owner.buildups!.control!.value,6);});
test('saved concentration has one owner channel, switches atomically, ends on incapacitation and can be dropped explicitly',()=>{const effect=control('ROOT',4),p=profile([ability({key:'bind',targetSide:'ENEMY',area:'SINGLE',manaCost:1,resourceCost:{},check:undefined,concentration:true,effect:{kind:'EFFECT',effectIds:['effect.control']}})]);p.abilities[0]!.grants=[grant(effect)];p.abilities.push({...structuredClone(p.abilities[0]!),key:'shift',id:'class.mage.shift',action:'QUICK'});const hero=unit('hero','PARTY',3);hero.techniques=p;let s=startTactical(controlledRules,[hero,unit('enemy','ENEMY',2),unit('enemy.other','ENEMY',1)]);s=stepTactical(controlledRules,s,0,{actorId:'hero',kind:'TECHNIQUE',abilityId:'class.mage.bind',targetId:'enemy',draws:[{targetId:'enemy'}]}).state;assert.ok(s.units[0]!.concentration);assert.equal(s.units[1]!.effects![0]!.concentrationId,s.units[0]!.concentration!.token);const switched=stepTactical(controlledRules,s,1,{actorId:'hero',kind:'TECHNIQUE',abilityId:'class.mage.shift',targetId:'enemy.other',draws:[{targetId:'enemy.other'}]});assert.equal(switched.evidence.technique!.concentrationEnded!.token,s.units[0]!.concentration!.token);assert.equal(switched.state.units[1]!.effects!.length,0);assert.equal(switched.state.units[2]!.effects![0]!.concentrationId,switched.state.units[0]!.concentration!.token);assert.equal(s.units[1]!.effects!.length,1);const dropped=stepTactical(controlledRules,switched.state,2,{actorId:'hero',kind:'DROP_CONCENTRATION'}).state;assert.equal(dropped.units[2]!.effects!.length,0);assert.equal(dropped.units[0]!.concentration,undefined);s.units[0]!.health=0;s.units[0]!.state='DOWNED';s.cursor=1;const ended=stepTactical(controlledRules,s,1,{actorId:'enemy',kind:'END'}).state;assert.equal(ended.units[1]!.effects!.length,0);assert.equal(ended.units[0]!.concentration,undefined);});
test('surprise penalizes individual initiative and first-round budgets without changing base stats',()=>{const r={...rules,surprise:[{unitId:'hero',initiativePenalty:10,loseMain:true,loseQuick:true,loseReaction:true}]},s=startTactical(r,[unit('hero','PARTY',3),unit('enemy','ENEMY',2)]);assert.deepEqual(s.order,['enemy','hero']);assert.deepEqual(s.budgets.hero,{main:0,quick:0,reaction:0});assert.equal(s.units[0]!.stats.initiative,3);let next=stepTactical(r,s,0,{actorId:'enemy',kind:'END'}).state;next=stepTactical(r,next,1,{actorId:'hero',kind:'END'}).state;assert.equal(next.round,2);assert.deepEqual(next.budgets.hero,{main:1,quick:1,reaction:1});});
test('leaving engagement triggers only an owned affordable opportunity ability and spends one Reaction, using the same typed attack pipeline',()=>{const enemy=unit('enemy','ENEMY',2);enemy.techniques=profile([ability({key:'opportunity',minimumNativeLevel:0,action:'REACTION',delivery:'MARTIAL',area:'SINGLE',range:0,manaCost:0,resourceCost:{},cooldownRounds:0})]);const s=startTactical(rules,[unit('hero','PARTY',3),enemy]);assert.throws(()=>stepTactical(rules,s,0,{actorId:'hero',kind:'MOVE',zone:'balcony'}),/OPPORTUNITY/);const reaction={actorId:'enemy',kind:'TECHNIQUE' as const,abilityId:'class.mage.opportunity',targetId:'hero',draws:[{targetId:'hero',roll:20,amount:8}]};const moved=stepTactical(rules,s,0,{actorId:'hero',kind:'MOVE',zone:'balcony',opportunities:[reaction]});assert.equal(moved.state.units[0]!.health,12);assert.equal(moved.state.units[0]!.zone,'balcony');assert.equal(moved.state.budgets.enemy!.reaction,0);assert.equal(moved.state.budgets.hero!.quick,0);assert.equal(moved.evidence.opportunityEvents!.length,1);assert.deepEqual(stepTactical(rules,s,0,moved.evidence.intent),moved);});

import { deriveDamageProfile,resistanceFor,type TypedDamageRules } from '../src/domains/tactical-damage.js';
import { deriveCarryEffects } from '../src/domains/tactical-persistence.js';
import type { TacticalSpec } from '../src/domains/tactical-content.js';
test('conditional defense evaluates current owner tags, sums raw contributions before capping, and does not mutate the pinned profile',()=>{const r:TypedDamageRules={version:3,types:['fire'],defaultType:'fire',resistanceStacking:'SUM_CAPPED',families:{elemental:['fire']},conditionalTags:['wet']},p=deriveDamageProfile(r,[{nativeLevel:0,traits:{version:2,minimumNativeLevel:0,resistances:{fire:10000},conditional:[{type:'fire',ownerTag:'wet',resistanceBps:-5000}]}},{nativeLevel:0,traits:{version:1,minimumNativeLevel:0,resistances:{fire:5000}}}]);const before=structuredClone(p);assert.equal(resistanceFor(p,'fire'),10000);assert.equal(resistanceFor(p,'fire',['wet']),10000);assert.deepEqual(p,before);const vulnerable=deriveDamageProfile(r,[{nativeLevel:0,traits:{version:2,minimumNativeLevel:0,conditional:[{type:'fire',ownerTag:'wet',resistanceBps:-5000}]}}]);assert.equal(resistanceFor(vulnerable,'fire'),0);assert.equal(resistanceFor(vulnerable,'fire',['wet']),-5000);});
test('persistent encounter and Turn clocks advance only at settlement, while Until Cleansed remains until explicit removal',()=>{const s=initial(),effect=control('ROOT',4);s.units[0]!.effects=[{...grant({...effect,clock:'ENCOUNTERS',tick:'ENCOUNTER_END'}),sourceUnitId:'enemy',appliedRevision:0,remaining:2},{...grant({...effect,family:'turns',clock:'ADVENTURE_TURNS',tick:'TURN_SPEND'}),sourceUnitId:'enemy',appliedRevision:0,remaining:3},{...grant({...effect,family:'curse',clock:'UNTIL_CLEANSED',tick:'NONE'}),sourceUnitId:'enemy',appliedRevision:0,remaining:1}];s.outcome='RETREAT';const spec={rules,ruleset:'TACTICAL_ENCOUNTER_V1',version:1,playerZone:'floor',allies:[],enemies:[],failure:{destination:'HOME',turnCost:2,recoveryHealth:1}} as TacticalSpec;const before=structuredClone(s),after=deriveCarryEffects(spec,s,2);assert.deepEqual(after.map(e=>[e.effect.family,e.remaining]),[['control',1],['curse',1]]);assert.deepEqual(s,before);});
test('save checks use defender attributes and earned rank, and explicit status bypass does not mutate their original immunity',()=>{const a=ability({key:'bind',targetSide:'ENEMY',area:'SINGLE',bypassStatusImmunity:true,check:{mode:'SAVE',attribute:'wisdom',skillId:'skill.magic',difficulty:15,modifier:0},effect:{kind:'EFFECT',effectIds:['effect.control']}}),hero=unit('hero','PARTY',3),enemy=unit('enemy','ENEMY',2);hero.techniques=profile([a]);enemy.statusProfile={version:2,immuneTags:['control'],durationReductionBps:{}};const s=startTactical(controlledRules,[hero,enemy]);const saved=stepTactical(controlledRules,s,0,{kind:'TECHNIQUE',actorId:'hero',abilityId:'class.mage.bind',targetId:'enemy',draws:[{targetId:'enemy',roll:10}]});assert.equal(saved.evidence.technique!.events[0]!.check!.proficiency,4);assert.equal(saved.state.units[1]!.effects!.length,0);const failed=stepTactical(controlledRules,s,0,{kind:'TECHNIQUE',actorId:'hero',abilityId:'class.mage.bind',targetId:'enemy',draws:[{targetId:'enemy',roll:1}]});assert.equal(failed.state.units[1]!.effects!.length,1);assert.deepEqual(failed.state.units[1]!.statusProfile!.immuneTags,['control']);});

test('repeated hard control converts to Dazed even in Refresh families, so repeated Stun cannot remove every enemy turn',()=>{const effect={...control('STUN',2),stacking:'REFRESH'} as RoundEffect,owner:TacticalUnit={...unit('enemy','ENEMY',1),effects:[],buildups:{}},source={id:'hero',onHitEffects:[grant(effect)]};applyOnHitEffects(owner,source,1);assert.equal(json(owner.effects![0]!.effect).control,'STUN');const second=applyOnHitEffects(owner,source,2);assert.equal(second[0]!.kind,'CONVERTED');assert.equal(second.at(-1)!.kind,'REPLACED');assert.equal(json(owner.effects![0]!.effect).control,'DAZED');});

test('an opportunity strike that incapacitates the mover ends their turn and lets another party member revive them',()=>{const hero=unit('hero','PARTY',3);hero.health=1;const enemy=unit('enemy','ENEMY',2);enemy.techniques=profile([ability({key:'opportunity',minimumNativeLevel:0,action:'REACTION',area:'SINGLE',range:0,manaCost:0,resourceCost:{},cooldownRounds:0})]);const ally=unit('ally','PARTY',1);ally.canHeal=true;const s=startTactical(rules,[hero,enemy,ally]),moved=stepTactical(rules,s,0,{actorId:'hero',kind:'MOVE',zone:'balcony',opportunities:[{actorId:'enemy',kind:'TECHNIQUE',abilityId:'class.mage.opportunity',targetId:'hero',draws:[{targetId:'hero',roll:20,amount:8}]}]});assert.equal(moved.state.units[0]!.state,'DOWNED');assert.equal(moved.state.units[0]!.zone,'floor');assert.equal(moved.state.outcome,null);assert.equal(moved.state.order[moved.state.cursor],'enemy');assert.equal(moved.evidence.turnInterrupted,true);const ended=stepTactical(rules,moved.state,1,{actorId:'enemy',kind:'END'}).state;const healed=stepTactical(rules,ended,2,{actorId:'ally',kind:'HEAL',targetId:'hero'}).state;assert.equal(healed.units[0]!.health,5);assert.equal(healed.units[0]!.state,'ACTIVE');assert.deepEqual(stepTactical(rules,s,0,moved.evidence.intent),moved);});
