import { Ajv } from 'ajv';
import type pg from 'pg';
import { DomainError } from '../foundation/errors.js';
import { attributes,type StartingAttributes } from './build-content.js';
import { resolveCheck,resolveAttack,type MechanicsSource } from './character-mechanics.js';
import type { ContentEntity } from './content.js';
import type { StatusEvent } from './tactical-status.js';
import { resistanceFor } from './tactical-damage.js';
import { effectStats,applyOnHealEffects,applyOnHitEffects,validatePeriodicGrants,validateRoundEffect,normalizeEffectGrants,type EffectGrant } from './tactical-effects.js';
import { tacticalDistance,type TacticalRules,type TacticalState,type TacticalUnit } from './tactical-engine.js';

/** Additional authored actions share the saved transition and journal. Existing
 * single-ability contracts and their historical evidence remain unchanged. */
export type TechniqueCheck={mode:'ATTACK'|'SAVE';attribute:typeof attributes[number];skillId:string;difficulty:number;modifier:number};
export type TechniqueSpec={key:string;delivery?:'MAGICAL'|'MARTIAL'|'OTHER';concentration?:boolean;bypassStatusImmunity?:boolean;minimumNativeLevel:number;action:'MAIN'|'QUICK'|'REACTION';targetSide:'ALLY'|'ENEMY';range:number;area:'SINGLE'|'ZONE';manaCost:number;resourceCost:Record<string,number>;cooldownRounds:number;check?:TechniqueCheck;effect:
 {kind:'DAMAGE';type:string;min:number;max:number;penetration:number}|
 {kind:'HEAL'|'RESURRECT';min:number;max:number}|
 {kind:'STABILIZE'}|{kind:'EFFECT';effectIds:string[]}};
export type TechniquePack={version:1;resources:{key:string;maximum:number;clock:'ENCOUNTER'}[];abilities:TechniqueSpec[]};
export type Technique=TechniqueSpec&{id:string;sourceId:string;sourceRevision:number;sourceInstanceIds:string[];grants:EffectGrant[]};
export type TechniqueProfile={version:1;abilities:Technique[];maximums:Record<string,number>};
export type TechniqueDraw={targetId:string;roll?:number;amount?:number};
export type TechniqueIntent={actorId:string;kind:'TECHNIQUE';targetId:string;abilityId:string;draws:TechniqueDraw[]};
export type TechniqueEvent={actorId:string;targetId:string;abilityId:string;sourceRevision:number;sourceInstanceIds:string[];check:ReturnType<typeof resolveCheck>|null;damage:ReturnType<typeof resolveAttack>|null;amount:number;healthBefore:number;healthAfter:number;stateBefore:TacticalUnit['state'];stateAfter:TacticalUnit['state'];stabilized:boolean};
const keyShape={type:'string',pattern:'^[a-z][a-z0-9_-]{0,39}$'},token={type:'string',pattern:'^[a-z][a-z0-9_.-]{0,63}$'},id={type:'string',pattern:'^[a-z][a-z0-9_.-]{2,119}$'},n=(min:number,max=1000000)=>({type:'integer',minimum:min,maximum:max});
const shape=new Ajv({strict:true}).compile({type:'object',additionalProperties:false,required:['version','resources','abilities'],properties:{version:{const:1},resources:{type:'array',maxItems:8,items:{type:'object',additionalProperties:false,required:['key','maximum','clock'],properties:{key:keyShape,maximum:n(1),clock:{const:'ENCOUNTER'}}}},abilities:{type:'array',minItems:1,maxItems:16,items:{type:'object',additionalProperties:false,required:['key','minimumNativeLevel','action','targetSide','range','area','manaCost','resourceCost','cooldownRounds','effect'],properties:{delivery:{enum:['MAGICAL','MARTIAL','OTHER']},concentration:{type:'boolean'},bypassStatusImmunity:{type:'boolean'},key:keyShape,minimumNativeLevel:n(0,999),action:{enum:['MAIN','QUICK','REACTION']},targetSide:{enum:['ALLY','ENEMY']},range:n(0,31),area:{enum:['SINGLE','ZONE']},manaCost:n(0),resourceCost:{type:'object',maxProperties:8,propertyNames:keyShape,additionalProperties:n(1)},cooldownRounds:n(0,100),check:{type:'object',additionalProperties:false,required:['mode','attribute','skillId','difficulty','modifier'],properties:{mode:{enum:['ATTACK','SAVE']},attribute:{enum:attributes},skillId:id,difficulty:n(-1000000),modifier:n(-1000,1000)}},effect:{oneOf:[{type:'object',additionalProperties:false,required:['kind','type','min','max','penetration'],properties:{kind:{const:'DAMAGE'},type:token,min:n(1),max:n(1),penetration:n(0)}},{type:'object',additionalProperties:false,required:['kind','min','max'],properties:{kind:{enum:['HEAL','RESURRECT']},min:n(1),max:n(1)}},{type:'object',additionalProperties:false,required:['kind'],properties:{kind:{const:'STABILIZE'}}},{type:'object',additionalProperties:false,required:['kind','effectIds'],properties:{kind:{const:'EFFECT'},effectIds:{type:'array',minItems:1,maxItems:8,uniqueItems:true,items:id}}}]}}}}}});
const fail=(code:string):never=>{throw new DomainError(409,code);};
export function validateTechniquePack(value:unknown):asserts value is TechniquePack {
 if(!shape(value))throw new DomainError(400,'INVALID_TACTICAL_TECHNIQUES');const p=value as TechniquePack;
 if(new Set(p.abilities.map(a=>a.key)).size!==p.abilities.length||new Set(p.resources.map(a=>a.key)).size!==p.resources.length||p.abilities.some(a=>Object.keys(a.resourceCost).some(k=>!p.resources.some(r=>r.key===k&&r.maximum>=a.resourceCost[k]!))||('max' in a.effect&&a.effect.max<a.effect.min)||(['HEAL','RESURRECT','STABILIZE'].includes(a.effect.kind)&&a.targetSide!=='ALLY')||(a.effect.kind==='DAMAGE'&&(!a.check||a.check.mode!=='ATTACK'))||(a.effect.kind!=='DAMAGE'&&a.check?.mode==='ATTACK')||(a.action==='REACTION'&&(a.effect.kind!=='DAMAGE'||a.area!=='SINGLE'||a.range!==0||a.targetSide!=='ENEMY'))||(a.concentration&&a.effect.kind!=='EFFECT')||(a.bypassStatusImmunity&&a.effect.kind!=='EFFECT')||(a.effect.kind==='RESURRECT'&&a.manaCost===0&&Object.keys(a.resourceCost).length===0)))throw new DomainError(400,'INVALID_TACTICAL_TECHNIQUES');
}
export function techniqueProfile(source:ContentEntity,p:TechniquePack,effects:Map<string,ContentEntity>):TechniqueProfile {
 validateTechniquePack(p);return {version:1,maximums:Object.fromEntries(p.resources.map(r=>[`${source.id}.${r.key}`,r.maximum])),abilities:p.abilities.map(a=>({...structuredClone(a),id:`${source.id}.${a.key}`,sourceId:source.id,sourceRevision:source.revision,sourceInstanceIds:[],resourceCost:Object.fromEntries(Object.entries(a.resourceCost).map(([k,v])=>[`${source.id}.${k}`,v])),grants:a.effect.kind==='EFFECT'?normalizeEffectGrants(a.effect.effectIds.map(effectId=>{const e=effects.get(effectId);validateRoundEffect(e?.definition.mechanics?.tacticalRoundEffect);return {effectId,effectRevision:e!.revision,sourceId:source.id,sourceRevision:source.revision,effect:e!.definition.mechanics!.tacticalRoundEffect} as EffectGrant;})):[]}))};
}
export function validateTechniqueContent(e:ContentEntity,entities:Map<string,ContentEntity>){
 const m=e.definition.mechanics,p=m?.tacticalTechniques;if(p===undefined)return;validateTechniquePack(p);
 const native=e.kind==='CLASS'&&m!.classProgression!==undefined,template=['NPC','MONSTER'].includes(e.kind)&&m!.tacticalUnit!==undefined,selected=(e.kind==='ABILITY'&&(m!.feat!==undefined||m!.subclass!==undefined))||(e.kind==='ITEM'&&m!.equipment!==undefined);
 if(!(template||((native||selected)&&m!.combatModifiers!==undefined))||p.abilities.some(a=>native?(a.minimumNativeLevel<1||a.minimumNativeLevel>(m!.classProgression as {maximumNativeLevel:number}).maximumNativeLevel):a.minimumNativeLevel!==0))throw new DomainError(400,'INVALID_TACTICAL_TECHNIQUE_SOURCE');
 for(const a of p.abilities){if(a.check&&(!e.definition.dependencies.includes(a.check.skillId)||entities.get(a.check.skillId)?.kind!=='SKILL'))throw new DomainError(400,'INVALID_TACTICAL_TECHNIQUE_SKILL');if(a.effect.kind==='EFFECT')for(const effectId of a.effect.effectIds)if(!e.definition.dependencies.includes(effectId)||entities.get(effectId)?.kind!=='EFFECT')throw new DomainError(400,'INVALID_TACTICAL_TECHNIQUE_EFFECT');}
 techniqueProfile(e,p,entities);
}
export async function loadTechniqueProfile(client:pg.PoolClient,releaseId:string,sources:Pick<MechanicsSource,'entityId'|'revision'|'nativeLevel'|'instanceId'>[]):Promise<TechniqueProfile>{
 const result:TechniqueProfile={version:1,abilities:[],maximums:{}};
 if(!sources.length)return result;
 const rows=(await client.query(`SELECT v.entity_id,v.revision,e.kind,v.definition FROM content_versions v JOIN content_entities e ON e.id=v.entity_id WHERE (v.entity_id,v.revision) IN (SELECT * FROM unnest($1::text[],$2::integer[]))`,[sources.map(s=>s.entityId),sources.map(s=>s.revision)])).rows;
 const bySource=new Map(rows.map(row=>[`${row.entity_id}:${row.revision}`,row])),effectIds=new Set<string>(),activeIds=new Set<string>();
 for(const source of sources){const p=bySource.get(`${source.entityId}:${source.revision}`)?.definition.mechanics?.tacticalTechniques;if(!p)continue;validateTechniquePack(p);for(const a of p.abilities){if(source.nativeLevel>=a.minimumNativeLevel)activeIds.add(`${source.entityId}.${a.key}`);if(a.effect.kind==='EFFECT')for(const id of a.effect.effectIds)effectIds.add(id);}}
 if(activeIds.size>64)fail('TOO_MANY_TACTICAL_TECHNIQUES');
 const effects=new Map<string,ContentEntity>();
 if(effectIds.size){const pinned=(await client.query(`SELECT e.entity_id,e.revision,v.definition FROM release_entries e JOIN content_versions v ON v.entity_id=e.entity_id AND v.revision=e.revision JOIN content_entities ce ON ce.id=e.entity_id AND ce.kind='EFFECT' WHERE e.release_id=$1 AND e.entity_id=ANY($2::text[])`,[releaseId,[...effectIds]])).rows;for(const e of pinned)effects.set(e.entity_id,{id:e.entity_id,kind:'EFFECT',revision:e.revision,schemaVersion:1,definition:e.definition});if(effects.size!==effectIds.size)fail('TACTICAL_TECHNIQUE_EFFECT_NOT_PINNED');}
 for(const source of sources){const row=bySource.get(`${source.entityId}:${source.revision}`),p=row?.definition.mechanics?.tacticalTechniques;if(!p)continue;
  const profile=techniqueProfile({id:source.entityId,revision:source.revision,kind:row!.kind,schemaVersion:1,definition:row!.definition},p,effects);
  for(const a of profile.abilities){if(source.nativeLevel<a.minimumNativeLevel)continue;const prior=result.abilities.find(v=>v.id===a.id);if(prior){if(prior.sourceRevision!==a.sourceRevision)fail('CONFLICTING_TACTICAL_TECHNIQUE');if(source.instanceId)prior.sourceInstanceIds=[...new Set([...prior.sourceInstanceIds,source.instanceId])].sort();}else result.abilities.push({...a,sourceInstanceIds:source.instanceId?[source.instanceId]:[]});}
  Object.assign(result.maximums,profile.maximums);
 }
 result.abilities.sort((a,b)=>a.id<b.id?-1:a.id>b.id?1:0);return result;
}
export async function loadTechniqueSkills(client:pg.PoolClient,runId:string,cutoff:Date|string){
 return Object.fromEntries((await client.query('SELECT skill_id,max(after_rank)::integer AS rank FROM run_proficiency_choices WHERE run_id=$1 AND created_at<=$2 GROUP BY skill_id ORDER BY skill_id',[runId,cutoff])).rows.map(r=>[r.skill_id,r.rank])) as Record<string,number>;
}
export function validateTechniqueProfile(r:TacticalRules,p:TechniqueProfile){
 if(p.version!==1||p.abilities.length>64||new Set(p.abilities.map(a=>a.id)).size!==p.abilities.length)fail('INVALID_TACTICAL_TECHNIQUE_PROFILE');
 for(const a of p.abilities){const resourceCost=Object.fromEntries(Object.entries(a.resourceCost).map(([k,v])=>[k.slice(a.sourceId.length+1),v]));validateTechniquePack({version:1,resources:Object.entries(p.maximums).filter(([k])=>k.startsWith(`${a.sourceId}.`)).map(([k,maximum])=>({key:k.slice(a.sourceId.length+1),maximum,clock:'ENCOUNTER'})),abilities:[{...Object.fromEntries(Object.entries(a).filter(([k])=>!['id','sourceId','sourceRevision','sourceInstanceIds','grants'].includes(k))),resourceCost}]});
  if(a.id!==`${a.sourceId}.${a.key}`||!Number.isInteger(a.sourceRevision)||a.sourceRevision<1||a.sourceInstanceIds.some(v=>!/^[0-9a-f-]{36}$/.test(v)))fail('INVALID_TACTICAL_TECHNIQUE_PROFILE');if(a.effect.kind==='DAMAGE'&&!r.typedDamage?.types.includes(a.effect.type))fail('UNKNOWN_TACTICAL_TECHNIQUE_DAMAGE_TYPE');if(a.effect.kind==='EFFECT'){if(!r.roundEffects)fail('TACTICAL_TECHNIQUE_EFFECTS_DISABLED');if(a.concentration&&a.grants.some(g=>g.effect.clock!=='ROUNDS'))fail('TACTICAL_CONCENTRATION_REQUIRES_ROUND_CLOCK');normalizeEffectGrants(a.grants);validatePeriodicGrants(a.grants,r.roundEffects!.version,r.typedDamage?.types);if(a.grants.length!==a.effect.effectIds.length||a.grants.some(g=>!('effectIds' in a.effect)||!a.effect.effectIds.includes(g.effectId)))fail('INVALID_TACTICAL_TECHNIQUE_PROFILE');}
 }
}
export function techniqueTargets(r:TacticalRules,s:TacticalState,actor:TacticalUnit,a:Technique,targetId:string){
 const anchor=s.units.find(u=>u.id===targetId);if(!anchor||tacticalDistance(r,actor.zone,anchor.zone)>a.range)fail('ILLEGAL_TACTICAL_TECHNIQUE_TARGET');
 const legal=(u:TacticalUnit)=>(a.targetSide==='ALLY'?u.side===actor.side:u.side!==actor.side)&&(a.effect.kind==='RESURRECT'?u.state==='DEFEATED':a.effect.kind==='STABILIZE'?u.state==='DOWNED':a.effect.kind==='HEAL'?u.state!=='DEFEATED':u.state==='ACTIVE');
 if(!legal(anchor!))fail('ILLEGAL_TACTICAL_TECHNIQUE_TARGET');return (a.area==='SINGLE'?[anchor!]:s.units.filter(u=>u.zone===anchor!.zone&&legal(u))).sort((a,b)=>a.id<b.id?-1:1);
}
export function techniqueAvailable(s:TacticalState,actor:TacticalUnit,a:Technique){return s.budgets[actor.id]![a.action==='MAIN'?'main':a.action==='QUICK'?'quick':'reaction']===1&&(actor.mana??0)>=a.manaCost&&(actor.techniqueCooldowns?.[a.id]??0)<=s.round&&Object.entries(a.resourceCost).every(([k,v])=>(actor.techniqueResources?.[k]??0)>=v);}
export function useTechnique(r:TacticalRules,s:TacticalState,intent:TechniqueIntent,opportunity=false){
 const actor=s.units.find(u=>u.id===intent.actorId)!,a=actor.techniques?.abilities.find(a=>a.id===intent.abilityId);if(!r.techniques||!a||((a.action==='REACTION')!==opportunity)||!techniqueAvailable(s,actor,a))fail('ILLEGAL_TACTICAL_TECHNIQUE');
 const ability=a!,controls=new Set((actor.effects??[]).flatMap(e=>e.effect.version===4&&e.effect.control?[e.effect.control]:[]));if((ability.delivery==='MAGICAL'&&controls.has('SILENCE'))||(ability.delivery==='MARTIAL'&&controls.has('DISARM')))fail('TACTICAL_TECHNIQUE_SUPPRESSED');if(ability.bypassStatusImmunity&&r.statusDefense?.version!==2)fail('TACTICAL_STATUS_BYPASS_DISABLED');
 const concentrationEnded=ability.concentration?dropConcentration(s,actor.id):null;
 const targets=techniqueTargets(r,s,actor,ability,intent.targetId);if(!Array.isArray(intent.draws)||intent.draws.length!==targets.length||intent.draws.some((d,i)=>d.targetId!==targets[i]!.id))fail('INVALID_TACTICAL_TECHNIQUE_DRAWS');
 const statusEvents:StatusEvent[]=[],events:TechniqueEvent[]=[],effectEvents:ReturnType<typeof applyOnHitEffects>=[];
 actor.mana=(actor.mana??0)-ability.manaCost;for(const [k,v] of Object.entries(ability.resourceCost))actor.techniqueResources![k]!-=v;actor.techniqueCooldowns![ability.id]=s.round+ability.cooldownRounds+1;s.budgets[actor.id]![ability.action==='MAIN'?'main':ability.action==='QUICK'?'quick':'reaction']=0;
 for(let i=0;i<targets.length;i++){const target=targets[i]!,d=intent.draws[i]!,healthBefore=target.health,stateBefore=target.state;if('min' in ability.effect&&(!Number.isInteger(d.amount)||d.amount!<ability.effect.min||d.amount!>ability.effect.max))fail('INVALID_TACTICAL_TECHNIQUE_DRAWS');
  let check:ReturnType<typeof resolveCheck>|null=null,damage:ReturnType<typeof resolveAttack>|null=null,amount=0;
  if(ability.check){const c=ability.check,checked=c.mode==='SAVE'?target:actor;if(!Number.isInteger(d.roll)||d.roll!<1||d.roll!>20)fail('INVALID_TACTICAL_TECHNIQUE_DRAWS');const input={roll:d.roll!,attributeScore:checked.checkAttributes![c.attribute],proficiencyRank:checked.checkSkills&&Object.hasOwn(checked.checkSkills,c.skillId)?checked.checkSkills[c.skillId]!:0,situationalModifier:Math.max(-1000000,Math.min(1000000,c.modifier+(c.mode==='ATTACK'?effectStats(actor).accuracy:0))),difficulty:c.mode==='ATTACK'?effectStats(target).evasion:c.difficulty};check=resolveCheck(r.damage.check,input);
   if(ability.effect.kind==='DAMAGE'){const e=ability.effect;if(!Number.isInteger(d.amount)||d.amount!<e.min||d.amount!>e.max)fail('INVALID_TACTICAL_TECHNIQUE_DRAWS');const reacting=Boolean(target.guardReady&&target.canGuard&&!(target.effects??[]).some(e=>e.effect.version===4&&['STUN','REACTION_LOCK'].includes(e.effect.control??''))&&s.budgets[target.id]!.reaction===1);damage=resolveAttack(r.damage,{check:input,rawDamage:d.amount!,armor:Math.min(1000000,effectStats(target).armor+(reacting?(r.guardArmorBonus??0):0)),penetration:e.penetration,resistanceBps:resistanceFor(target.damageProfile,e.type,target.effects?.flatMap(e=>e.effect.tags)??[])});if(reacting){target.guardReady=false;s.budgets[target.id]!.reaction=0;}amount=damage.damage;target.health=Math.max(0,target.health-amount);if(target.health===0){target.state=target.side==='ENEMY'?'DEFEATED':'DOWNED';target.guardReady=false;}}
  }else if(d.roll!==undefined)fail('INVALID_TACTICAL_TECHNIQUE_DRAWS');
  const succeeds=!check||(ability.check!.mode==='SAVE'?!check.success:check.success);
  if(ability.effect.kind!=='DAMAGE'&&succeeds){const e=ability.effect;if(e.kind==='HEAL'||e.kind==='RESURRECT'){if(!Number.isInteger(d.amount)||d.amount!<e.min||d.amount!>e.max)fail('INVALID_TACTICAL_TECHNIQUE_DRAWS');amount=d.amount!;target.health=Math.min(target.stats.maxHealth,target.health+amount);target.state='ACTIVE';target.strikes=0;target.stabilized=false;}else if(e.kind==='STABILIZE'){target.stabilized=true;}else if(e.kind==='EFFECT'){const oldProfile=target.statusProfile;if(ability.bypassStatusImmunity&&oldProfile)target.statusProfile={...oldProfile,immuneTags:[]};effectEvents.push(...applyOnHitEffects(target,{id:actor.id,onHitEffects:ability.grants},s.revision+1,r.statusDefense?statusEvents:undefined));target.statusProfile=oldProfile;if(ability.concentration)for(const active of target.effects??[])if(active.sourceUnitId===actor.id&&active.appliedRevision===s.revision+1){active.concentrationId=`${actor.id}.${s.revision+1}`;actor.concentration={token:active.concentrationId,abilityId:ability.id};}}}
  if(damage?.check.success&&target.state==='ACTIVE'&&r.roundEffects)effectEvents.push(...applyOnHitEffects(target,actor,s.revision+1,r.statusDefense?statusEvents:undefined));
  if(succeeds&&(ability.effect.kind==='HEAL'||ability.effect.kind==='RESURRECT')&&(r.roundEffects?.version??0)>=2)effectEvents.push(...applyOnHealEffects(target,actor,s.revision+1,r.statusDefense?statusEvents:undefined));
  if(!('min' in ability.effect)&&d.amount!==undefined)fail('INVALID_TACTICAL_TECHNIQUE_DRAWS');
  events.push({actorId:actor.id,targetId:target.id,abilityId:ability.id,sourceRevision:ability.sourceRevision,sourceInstanceIds:[...ability.sourceInstanceIds],check,damage,amount,healthBefore,healthAfter:target.health,stateBefore,stateAfter:target.state,stabilized:target.stabilized??false});
 }
 return {events,effectEvents,statusEvents,concentrationEnded,cost:{actorId:actor.id,abilityId:ability.id,mana:ability.manaCost,resources:structuredClone(ability.resourceCost),nextAvailableRound:actor.techniqueCooldowns![ability.id]}};
}

export function dropConcentration(s:TacticalState,actorId:string){const actor=s.units.find(u=>u.id===actorId)!,previous=actor.concentration;if(!previous)return null;for(const u of s.units)u.effects=(u.effects??[]).filter(e=>e.concentrationId!==previous.token);delete actor.concentration;return {actorId,...previous};}
export function reconcileConcentration(s:TacticalState){const ended=[];for(const actor of s.units)if(actor.concentration&&(actor.state!=='ACTIVE'||(actor.effects??[]).some(e=>e.effect.version===4&&e.effect.control==='STUN')||!s.units.some(u=>u.effects?.some(e=>e.concentrationId===actor.concentration!.token))))ended.push(dropConcentration(s,actor.id)!);return ended;}

export function opportunityAbilities(r:TacticalRules,s:TacticalState,mover:TacticalUnit,zone:string){if(!r.techniques)return [];return s.units.filter(u=>u.side!==mover.side&&u.state==='ACTIVE'&&u.zone===mover.zone&&zone!==u.zone&&!(u.effects??[]).some(e=>e.effect.version===4&&['STUN','REACTION_LOCK','DISARM'].includes(e.effect.control??''))).sort((a,b)=>a.id<b.id?-1:1).flatMap(actor=>{const ability=actor.techniques?.abilities.find(a=>a.action==='REACTION'&&techniqueAvailable(s,actor,a));return ability?[{actor,ability}]:[];});}
