import { deriveCarryEffects,loadInjuryGrant } from './tactical-persistence.js';
import type { EffectGrant } from './tactical-effects.js';
import type pg from 'pg';
import { executeAction,advanceRevision,type Envelope,type ActionContext } from '../foundation/action.js';
import { DomainError } from '../foundation/errors.js';
import type { ContentEntity } from './content.js';
import type { TacticalSpec } from './tactical-content.js';
import type { TacticalState } from './tactical-engine.js';
export function validateCompanionContent(e:ContentEntity){const m=e.definition.mechanics,value=m?.companion;if(value===undefined)return;if(e.kind!=='NPC'||m!.tacticalUnit===undefined||!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).sort().join(',')!=='access,version'||(value as {version?:number}).version!==1||(value as {access?:string}).access!=='DISCOVERED')throw new DomainError(400,'INVALID_TACTICAL_COMPANION');}
export function recruitCompanion(pool:pg.Pool,accountId:string,envelope:Envelope,companionId:string){
 if(envelope.actionType!=='RECRUIT_COMPANION'||!/^[a-z][a-z0-9_.-]{2,119}$/.test(companionId))throw new DomainError(400,'INVALID_COMPANION_RECRUITMENT');
 return executeAction(pool,accountId,envelope,{companionId},async c=>{if((await c.client.query('SELECT 1 FROM owned_companions WHERE account_id=$1 AND companion_id=$2',[accountId,companionId])).rows.length)throw new DomainError(409,'COMPANION_ALREADY_OWNED');if(!(await c.client.query('SELECT 1 FROM discoveries WHERE account_id=$1 AND entity_id=$2',[accountId,companionId])).rows.length)throw new DomainError(404,'COMPANION_NOT_DISCOVERED');const source=(await c.client.query("SELECT v.definition->'mechanics'->'companion' AS spec FROM release_entries e JOIN content_entities ce ON ce.id=e.entity_id AND ce.kind='NPC' JOIN content_versions v ON v.entity_id=e.entity_id AND v.revision=e.revision WHERE e.release_id=$1 AND e.entity_id=$2",[c.run.content_release_id,companionId])).rows[0]?.spec;if(source?.version!==1||source.access!=='DISCOVERED')throw new DomainError(409,'COMPANION_NOT_RECRUITABLE');if((await c.client.query("SELECT 1 FROM instance_participants p JOIN instances i ON i.id=p.instance_id WHERE p.run_id=$1 AND i.lifecycle='ACTIVE'",[c.run.id])).rows.length)throw new DomainError(409,'INSTANCE_STILL_ACTIVE');await c.client.query('INSERT INTO owned_companions(account_id,companion_id,run_id,action_id) VALUES($1,$2,$3,$4)',[accountId,companionId,c.run.id,c.actionId]);return {companionId,revision:await advanceRevision(c)};});
}
export async function companionPool(client:Pick<pg.PoolClient,'query'>,runId:string,companionId:string,recoveryId?:string|null){
 if(recoveryId===null)return null;const row=(await client.query(`SELECT id::text,health,mana,effects FROM companion_tactical_recoveries WHERE run_id=$1 AND companion_id=$2 ${recoveryId===undefined?'ORDER BY id DESC LIMIT 1':'AND id=$3'}`,[runId,companionId,...(recoveryId===undefined?[]:[recoveryId])])).rows[0];if(recoveryId!==undefined&&!row)throw new DomainError(409,'COMPANION_RECOVERY_NOT_PINNED');return row??null;
}
export async function requireCompanion(client:pg.PoolClient,accountId:string,companionId:string){if(!(await client.query('SELECT 1 FROM owned_companions WHERE account_id=$1 AND companion_id=$2',[accountId,companionId])).rows.length)throw new DomainError(403,'COMPANION_NOT_OWNED');}
export function companionRecovery(spec:TacticalSpec,state:TacticalState,unitId:string,turnCost=0,injury?:EffectGrant){const u=state.units.find(u=>u.id===unitId)!;return {health:u.health>0?u.health:Math.min(u.stats.maxHealth,spec.failure.recoveryHealth),mana:u.mana??0,terminalState:u.state,rescued:u.state!=='ACTIVE'&&state.outcome==='VICTORY',effects:spec.rules.roundEffects?.version===4?deriveCarryEffects(spec,state,turnCost,injury,unitId):[]};}
export async function settleCompanions(c:ActionContext,instanceId:string,spec:TacticalSpec,state:TacticalState,turnCost=0){
 const id=(await c.client.query('SELECT definition_id FROM encounter_records WHERE instance_id=$1',[instanceId])).rows[0].definition_id;
 const injury=spec.rules.roundEffects?.version===4?await loadInjuryGrant(c.client,c.run.content_release_id!,id,spec):undefined;
 for(const ally of spec.allies.filter(a=>a.owned)){const r=companionRecovery(spec,state,ally.id,turnCost,injury);await c.client.query('INSERT INTO companion_tactical_recoveries(instance_id,run_id,companion_id,action_id,health,mana,terminal_state,rescued,effects) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[instanceId,c.run.id,ally.definitionId,c.actionId,r.health,r.mana,r.terminalState,r.rescued,JSON.stringify(r.effects)]);}
}
export async function companionsView(pool:pg.Pool,accountId:string){return {companions:(await pool.query(`SELECT owned.companion_id AS "companionId",v.definition->>'name' AS name FROM owned_companions owned JOIN content_versions v ON v.entity_id=owned.companion_id AND v.revision=owned.companion_revision WHERE owned.account_id=$1 ORDER BY owned.companion_id`,[accountId])).rows};}
